// Code generated by protoc-gen-go. DO NOT EDIT.
// source: storage.proto

package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Ignoring public import of TimestampRange from common.proto

type CreateLinkRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateLinkRequest) Reset()         { *m = CreateLinkRequest{} }
func (m *CreateLinkRequest) String() string { return proto.CompactTextString(m) }
func (*CreateLinkRequest) ProtoMessage()    {}
func (*CreateLinkRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{0}
}
func (m *CreateLinkRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateLinkRequest.Unmarshal(m, b)
}
func (m *CreateLinkRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateLinkRequest.Marshal(b, m, deterministic)
}
func (m *CreateLinkRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateLinkRequest.Merge(m, src)
}
func (m *CreateLinkRequest) XXX_Size() int {
	return xxx_messageInfo_CreateLinkRequest.Size(m)
}
func (m *CreateLinkRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateLinkRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateLinkRequest proto.InternalMessageInfo

func (m *CreateLinkRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreateLinkRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreateLinkResponse struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CreateLinkResponse) Reset()         { *m = CreateLinkResponse{} }
func (m *CreateLinkResponse) String() string { return proto.CompactTextString(m) }
func (*CreateLinkResponse) ProtoMessage()    {}
func (*CreateLinkResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{1}
}
func (m *CreateLinkResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateLinkResponse.Unmarshal(m, b)
}
func (m *CreateLinkResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateLinkResponse.Marshal(b, m, deterministic)
}
func (m *CreateLinkResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateLinkResponse.Merge(m, src)
}
func (m *CreateLinkResponse) XXX_Size() int {
	return xxx_messageInfo_CreateLinkResponse.Size(m)
}
func (m *CreateLinkResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateLinkResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateLinkResponse proto.InternalMessageInfo

func (m *CreateLinkResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreateLinkResponse) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type ReadLinkRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadLinkRequest) Reset()         { *m = ReadLinkRequest{} }
func (m *ReadLinkRequest) String() string { return proto.CompactTextString(m) }
func (*ReadLinkRequest) ProtoMessage()    {}
func (*ReadLinkRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{2}
}
func (m *ReadLinkRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadLinkRequest.Unmarshal(m, b)
}
func (m *ReadLinkRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadLinkRequest.Marshal(b, m, deterministic)
}
func (m *ReadLinkRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadLinkRequest.Merge(m, src)
}
func (m *ReadLinkRequest) XXX_Size() int {
	return xxx_messageInfo_ReadLinkRequest.Size(m)
}
func (m *ReadLinkRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadLinkRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadLinkRequest proto.InternalMessageInfo

func (m *ReadLinkRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ReadLinkResponse struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ReadLinkResponse) Reset()         { *m = ReadLinkResponse{} }
func (m *ReadLinkResponse) String() string { return proto.CompactTextString(m) }
func (*ReadLinkResponse) ProtoMessage()    {}
func (*ReadLinkResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{3}
}
func (m *ReadLinkResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadLinkResponse.Unmarshal(m, b)
}
func (m *ReadLinkResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadLinkResponse.Marshal(b, m, deterministic)
}
func (m *ReadLinkResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadLinkResponse.Merge(m, src)
}
func (m *ReadLinkResponse) XXX_Size() int {
	return xxx_messageInfo_ReadLinkResponse.Size(m)
}
func (m *ReadLinkResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadLinkResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadLinkResponse proto.InternalMessageInfo

func (m *ReadLinkResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ReadLinkResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReadLinkResponse) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *ReadLinkResponse) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *ReadLinkResponse) GetDeletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

type UpdateLinkRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateLinkRequest) Reset()         { *m = UpdateLinkRequest{} }
func (m *UpdateLinkRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateLinkRequest) ProtoMessage()    {}
func (*UpdateLinkRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{4}
}
func (m *UpdateLinkRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateLinkRequest.Unmarshal(m, b)
}
func (m *UpdateLinkRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateLinkRequest.Marshal(b, m, deterministic)
}
func (m *UpdateLinkRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateLinkRequest.Merge(m, src)
}
func (m *UpdateLinkRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateLinkRequest.Size(m)
}
func (m *UpdateLinkRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateLinkRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateLinkRequest proto.InternalMessageInfo

func (m *UpdateLinkRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateLinkRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type UpdateLinkResponse struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *UpdateLinkResponse) Reset()         { *m = UpdateLinkResponse{} }
func (m *UpdateLinkResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateLinkResponse) ProtoMessage()    {}
func (*UpdateLinkResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{5}
}
func (m *UpdateLinkResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateLinkResponse.Unmarshal(m, b)
}
func (m *UpdateLinkResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateLinkResponse.Marshal(b, m, deterministic)
}
func (m *UpdateLinkResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateLinkResponse.Merge(m, src)
}
func (m *UpdateLinkResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateLinkResponse.Size(m)
}
func (m *UpdateLinkResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateLinkResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateLinkResponse proto.InternalMessageInfo

func (m *UpdateLinkResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateLinkResponse) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type DeleteLinkRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteLinkRequest) Reset()         { *m = DeleteLinkRequest{} }
func (m *DeleteLinkRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteLinkRequest) ProtoMessage()    {}
func (*DeleteLinkRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{6}
}
func (m *DeleteLinkRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteLinkRequest.Unmarshal(m, b)
}
func (m *DeleteLinkRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteLinkRequest.Marshal(b, m, deterministic)
}
func (m *DeleteLinkRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteLinkRequest.Merge(m, src)
}
func (m *DeleteLinkRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteLinkRequest.Size(m)
}
func (m *DeleteLinkRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteLinkRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteLinkRequest proto.InternalMessageInfo

func (m *DeleteLinkRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteLinkResponse struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DeletedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *DeleteLinkResponse) Reset()         { *m = DeleteLinkResponse{} }
func (m *DeleteLinkResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteLinkResponse) ProtoMessage()    {}
func (*DeleteLinkResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{7}
}
func (m *DeleteLinkResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteLinkResponse.Unmarshal(m, b)
}
func (m *DeleteLinkResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteLinkResponse.Marshal(b, m, deterministic)
}
func (m *DeleteLinkResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteLinkResponse.Merge(m, src)
}
func (m *DeleteLinkResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteLinkResponse.Size(m)
}
func (m *DeleteLinkResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteLinkResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteLinkResponse proto.InternalMessageInfo

func (m *DeleteLinkResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DeleteLinkResponse) GetDeletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

type CreateNamespaceRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateNamespaceRequest) Reset()         { *m = CreateNamespaceRequest{} }
func (m *CreateNamespaceRequest) String() string { return proto.CompactTextString(m) }
func (*CreateNamespaceRequest) ProtoMessage()    {}
func (*CreateNamespaceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{8}
}
func (m *CreateNamespaceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateNamespaceRequest.Unmarshal(m, b)
}
func (m *CreateNamespaceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateNamespaceRequest.Marshal(b, m, deterministic)
}
func (m *CreateNamespaceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateNamespaceRequest.Merge(m, src)
}
func (m *CreateNamespaceRequest) XXX_Size() int {
	return xxx_messageInfo_CreateNamespaceRequest.Size(m)
}
func (m *CreateNamespaceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateNamespaceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateNamespaceRequest proto.InternalMessageInfo

func (m *CreateNamespaceRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreateNamespaceRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreateNamespaceResponse struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CreateNamespaceResponse) Reset()         { *m = CreateNamespaceResponse{} }
func (m *CreateNamespaceResponse) String() string { return proto.CompactTextString(m) }
func (*CreateNamespaceResponse) ProtoMessage()    {}
func (*CreateNamespaceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{9}
}
func (m *CreateNamespaceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateNamespaceResponse.Unmarshal(m, b)
}
func (m *CreateNamespaceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateNamespaceResponse.Marshal(b, m, deterministic)
}
func (m *CreateNamespaceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateNamespaceResponse.Merge(m, src)
}
func (m *CreateNamespaceResponse) XXX_Size() int {
	return xxx_messageInfo_CreateNamespaceResponse.Size(m)
}
func (m *CreateNamespaceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateNamespaceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateNamespaceResponse proto.InternalMessageInfo

func (m *CreateNamespaceResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreateNamespaceResponse) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type ReadNamespaceRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadNamespaceRequest) Reset()         { *m = ReadNamespaceRequest{} }
func (m *ReadNamespaceRequest) String() string { return proto.CompactTextString(m) }
func (*ReadNamespaceRequest) ProtoMessage()    {}
func (*ReadNamespaceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{10}
}
func (m *ReadNamespaceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadNamespaceRequest.Unmarshal(m, b)
}
func (m *ReadNamespaceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadNamespaceRequest.Marshal(b, m, deterministic)
}
func (m *ReadNamespaceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadNamespaceRequest.Merge(m, src)
}
func (m *ReadNamespaceRequest) XXX_Size() int {
	return xxx_messageInfo_ReadNamespaceRequest.Size(m)
}
func (m *ReadNamespaceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadNamespaceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadNamespaceRequest proto.InternalMessageInfo

func (m *ReadNamespaceRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ReadNamespaceResponse struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ReadNamespaceResponse) Reset()         { *m = ReadNamespaceResponse{} }
func (m *ReadNamespaceResponse) String() string { return proto.CompactTextString(m) }
func (*ReadNamespaceResponse) ProtoMessage()    {}
func (*ReadNamespaceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{11}
}
func (m *ReadNamespaceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadNamespaceResponse.Unmarshal(m, b)
}
func (m *ReadNamespaceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadNamespaceResponse.Marshal(b, m, deterministic)
}
func (m *ReadNamespaceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadNamespaceResponse.Merge(m, src)
}
func (m *ReadNamespaceResponse) XXX_Size() int {
	return xxx_messageInfo_ReadNamespaceResponse.Size(m)
}
func (m *ReadNamespaceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadNamespaceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadNamespaceResponse proto.InternalMessageInfo

func (m *ReadNamespaceResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ReadNamespaceResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReadNamespaceResponse) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *ReadNamespaceResponse) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *ReadNamespaceResponse) GetDeletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

type UpdateNamespaceRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateNamespaceRequest) Reset()         { *m = UpdateNamespaceRequest{} }
func (m *UpdateNamespaceRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateNamespaceRequest) ProtoMessage()    {}
func (*UpdateNamespaceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{12}
}
func (m *UpdateNamespaceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateNamespaceRequest.Unmarshal(m, b)
}
func (m *UpdateNamespaceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateNamespaceRequest.Marshal(b, m, deterministic)
}
func (m *UpdateNamespaceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateNamespaceRequest.Merge(m, src)
}
func (m *UpdateNamespaceRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateNamespaceRequest.Size(m)
}
func (m *UpdateNamespaceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateNamespaceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateNamespaceRequest proto.InternalMessageInfo

func (m *UpdateNamespaceRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateNamespaceRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type UpdateNamespaceResponse struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *UpdateNamespaceResponse) Reset()         { *m = UpdateNamespaceResponse{} }
func (m *UpdateNamespaceResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateNamespaceResponse) ProtoMessage()    {}
func (*UpdateNamespaceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{13}
}
func (m *UpdateNamespaceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateNamespaceResponse.Unmarshal(m, b)
}
func (m *UpdateNamespaceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateNamespaceResponse.Marshal(b, m, deterministic)
}
func (m *UpdateNamespaceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateNamespaceResponse.Merge(m, src)
}
func (m *UpdateNamespaceResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateNamespaceResponse.Size(m)
}
func (m *UpdateNamespaceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateNamespaceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateNamespaceResponse proto.InternalMessageInfo

func (m *UpdateNamespaceResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateNamespaceResponse) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type DeleteNamespaceRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteNamespaceRequest) Reset()         { *m = DeleteNamespaceRequest{} }
func (m *DeleteNamespaceRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteNamespaceRequest) ProtoMessage()    {}
func (*DeleteNamespaceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{14}
}
func (m *DeleteNamespaceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteNamespaceRequest.Unmarshal(m, b)
}
func (m *DeleteNamespaceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteNamespaceRequest.Marshal(b, m, deterministic)
}
func (m *DeleteNamespaceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteNamespaceRequest.Merge(m, src)
}
func (m *DeleteNamespaceRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteNamespaceRequest.Size(m)
}
func (m *DeleteNamespaceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteNamespaceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteNamespaceRequest proto.InternalMessageInfo

func (m *DeleteNamespaceRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteNamespaceResponse struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DeletedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *DeleteNamespaceResponse) Reset()         { *m = DeleteNamespaceResponse{} }
func (m *DeleteNamespaceResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteNamespaceResponse) ProtoMessage()    {}
func (*DeleteNamespaceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{15}
}
func (m *DeleteNamespaceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteNamespaceResponse.Unmarshal(m, b)
}
func (m *DeleteNamespaceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteNamespaceResponse.Marshal(b, m, deterministic)
}
func (m *DeleteNamespaceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteNamespaceResponse.Merge(m, src)
}
func (m *DeleteNamespaceResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteNamespaceResponse.Size(m)
}
func (m *DeleteNamespaceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteNamespaceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteNamespaceResponse proto.InternalMessageInfo

func (m *DeleteNamespaceResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DeleteNamespaceResponse) GetDeletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

type CreateAliasRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	LinkId               string   `protobuf:"bytes,2,opt,name=link_id,json=linkId,proto3" json:"link_id,omitempty"`
	NamespaceId          string   `protobuf:"bytes,3,opt,name=namespace_id,json=namespaceId,proto3" json:"namespace_id,omitempty"`
	Urn                  string   `protobuf:"bytes,4,opt,name=urn,proto3" json:"urn,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAliasRequest) Reset()         { *m = CreateAliasRequest{} }
func (m *CreateAliasRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAliasRequest) ProtoMessage()    {}
func (*CreateAliasRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{16}
}
func (m *CreateAliasRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAliasRequest.Unmarshal(m, b)
}
func (m *CreateAliasRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAliasRequest.Marshal(b, m, deterministic)
}
func (m *CreateAliasRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAliasRequest.Merge(m, src)
}
func (m *CreateAliasRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAliasRequest.Size(m)
}
func (m *CreateAliasRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAliasRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAliasRequest proto.InternalMessageInfo

func (m *CreateAliasRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreateAliasRequest) GetLinkId() string {
	if m != nil {
		return m.LinkId
	}
	return ""
}

func (m *CreateAliasRequest) GetNamespaceId() string {
	if m != nil {
		return m.NamespaceId
	}
	return ""
}

func (m *CreateAliasRequest) GetUrn() string {
	if m != nil {
		return m.Urn
	}
	return ""
}

type CreateAliasResponse struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CreateAliasResponse) Reset()         { *m = CreateAliasResponse{} }
func (m *CreateAliasResponse) String() string { return proto.CompactTextString(m) }
func (*CreateAliasResponse) ProtoMessage()    {}
func (*CreateAliasResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{17}
}
func (m *CreateAliasResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAliasResponse.Unmarshal(m, b)
}
func (m *CreateAliasResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAliasResponse.Marshal(b, m, deterministic)
}
func (m *CreateAliasResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAliasResponse.Merge(m, src)
}
func (m *CreateAliasResponse) XXX_Size() int {
	return xxx_messageInfo_CreateAliasResponse.Size(m)
}
func (m *CreateAliasResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAliasResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAliasResponse proto.InternalMessageInfo

func (m *CreateAliasResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreateAliasResponse) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type ReadAliasRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadAliasRequest) Reset()         { *m = ReadAliasRequest{} }
func (m *ReadAliasRequest) String() string { return proto.CompactTextString(m) }
func (*ReadAliasRequest) ProtoMessage()    {}
func (*ReadAliasRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{18}
}
func (m *ReadAliasRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadAliasRequest.Unmarshal(m, b)
}
func (m *ReadAliasRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadAliasRequest.Marshal(b, m, deterministic)
}
func (m *ReadAliasRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadAliasRequest.Merge(m, src)
}
func (m *ReadAliasRequest) XXX_Size() int {
	return xxx_messageInfo_ReadAliasRequest.Size(m)
}
func (m *ReadAliasRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadAliasRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadAliasRequest proto.InternalMessageInfo

func (m *ReadAliasRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ReadAliasResponse struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	LinkId               string               `protobuf:"bytes,2,opt,name=link_id,json=linkId,proto3" json:"link_id,omitempty"`
	NamespaceId          string               `protobuf:"bytes,3,opt,name=namespace_id,json=namespaceId,proto3" json:"namespace_id,omitempty"`
	Urn                  string               `protobuf:"bytes,4,opt,name=urn,proto3" json:"urn,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt            *timestamp.Timestamp `protobuf:"bytes,7,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ReadAliasResponse) Reset()         { *m = ReadAliasResponse{} }
func (m *ReadAliasResponse) String() string { return proto.CompactTextString(m) }
func (*ReadAliasResponse) ProtoMessage()    {}
func (*ReadAliasResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{19}
}
func (m *ReadAliasResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadAliasResponse.Unmarshal(m, b)
}
func (m *ReadAliasResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadAliasResponse.Marshal(b, m, deterministic)
}
func (m *ReadAliasResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadAliasResponse.Merge(m, src)
}
func (m *ReadAliasResponse) XXX_Size() int {
	return xxx_messageInfo_ReadAliasResponse.Size(m)
}
func (m *ReadAliasResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadAliasResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadAliasResponse proto.InternalMessageInfo

func (m *ReadAliasResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ReadAliasResponse) GetLinkId() string {
	if m != nil {
		return m.LinkId
	}
	return ""
}

func (m *ReadAliasResponse) GetNamespaceId() string {
	if m != nil {
		return m.NamespaceId
	}
	return ""
}

func (m *ReadAliasResponse) GetUrn() string {
	if m != nil {
		return m.Urn
	}
	return ""
}

func (m *ReadAliasResponse) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *ReadAliasResponse) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *ReadAliasResponse) GetDeletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

type UpdateAliasRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	LinkId               string   `protobuf:"bytes,2,opt,name=link_id,json=linkId,proto3" json:"link_id,omitempty"`
	NamespaceId          string   `protobuf:"bytes,3,opt,name=namespace_id,json=namespaceId,proto3" json:"namespace_id,omitempty"`
	Urn                  string   `protobuf:"bytes,4,opt,name=urn,proto3" json:"urn,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateAliasRequest) Reset()         { *m = UpdateAliasRequest{} }
func (m *UpdateAliasRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateAliasRequest) ProtoMessage()    {}
func (*UpdateAliasRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{20}
}
func (m *UpdateAliasRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAliasRequest.Unmarshal(m, b)
}
func (m *UpdateAliasRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAliasRequest.Marshal(b, m, deterministic)
}
func (m *UpdateAliasRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAliasRequest.Merge(m, src)
}
func (m *UpdateAliasRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateAliasRequest.Size(m)
}
func (m *UpdateAliasRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAliasRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAliasRequest proto.InternalMessageInfo

func (m *UpdateAliasRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateAliasRequest) GetLinkId() string {
	if m != nil {
		return m.LinkId
	}
	return ""
}

func (m *UpdateAliasRequest) GetNamespaceId() string {
	if m != nil {
		return m.NamespaceId
	}
	return ""
}

func (m *UpdateAliasRequest) GetUrn() string {
	if m != nil {
		return m.Urn
	}
	return ""
}

type UpdateAliasResponse struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *UpdateAliasResponse) Reset()         { *m = UpdateAliasResponse{} }
func (m *UpdateAliasResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateAliasResponse) ProtoMessage()    {}
func (*UpdateAliasResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{21}
}
func (m *UpdateAliasResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAliasResponse.Unmarshal(m, b)
}
func (m *UpdateAliasResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAliasResponse.Marshal(b, m, deterministic)
}
func (m *UpdateAliasResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAliasResponse.Merge(m, src)
}
func (m *UpdateAliasResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateAliasResponse.Size(m)
}
func (m *UpdateAliasResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAliasResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAliasResponse proto.InternalMessageInfo

func (m *UpdateAliasResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateAliasResponse) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type DeleteAliasRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAliasRequest) Reset()         { *m = DeleteAliasRequest{} }
func (m *DeleteAliasRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteAliasRequest) ProtoMessage()    {}
func (*DeleteAliasRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{22}
}
func (m *DeleteAliasRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAliasRequest.Unmarshal(m, b)
}
func (m *DeleteAliasRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAliasRequest.Marshal(b, m, deterministic)
}
func (m *DeleteAliasRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAliasRequest.Merge(m, src)
}
func (m *DeleteAliasRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteAliasRequest.Size(m)
}
func (m *DeleteAliasRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAliasRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAliasRequest proto.InternalMessageInfo

func (m *DeleteAliasRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteAliasResponse struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DeletedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *DeleteAliasResponse) Reset()         { *m = DeleteAliasResponse{} }
func (m *DeleteAliasResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteAliasResponse) ProtoMessage()    {}
func (*DeleteAliasResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{23}
}
func (m *DeleteAliasResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAliasResponse.Unmarshal(m, b)
}
func (m *DeleteAliasResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAliasResponse.Marshal(b, m, deterministic)
}
func (m *DeleteAliasResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAliasResponse.Merge(m, src)
}
func (m *DeleteAliasResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteAliasResponse.Size(m)
}
func (m *DeleteAliasResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAliasResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAliasResponse proto.InternalMessageInfo

func (m *DeleteAliasResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DeleteAliasResponse) GetDeletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

type CreateTargetRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	LinkId               string   `protobuf:"bytes,2,opt,name=link_id,json=linkId,proto3" json:"link_id,omitempty"`
	Url                  string   `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Rule                 string   `protobuf:"bytes,4,opt,name=rule,proto3" json:"rule,omitempty"`
	BRule                string   `protobuf:"bytes,5,opt,name=b_rule,json=bRule,proto3" json:"b_rule,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTargetRequest) Reset()         { *m = CreateTargetRequest{} }
func (m *CreateTargetRequest) String() string { return proto.CompactTextString(m) }
func (*CreateTargetRequest) ProtoMessage()    {}
func (*CreateTargetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{24}
}
func (m *CreateTargetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTargetRequest.Unmarshal(m, b)
}
func (m *CreateTargetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTargetRequest.Marshal(b, m, deterministic)
}
func (m *CreateTargetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTargetRequest.Merge(m, src)
}
func (m *CreateTargetRequest) XXX_Size() int {
	return xxx_messageInfo_CreateTargetRequest.Size(m)
}
func (m *CreateTargetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTargetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTargetRequest proto.InternalMessageInfo

func (m *CreateTargetRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreateTargetRequest) GetLinkId() string {
	if m != nil {
		return m.LinkId
	}
	return ""
}

func (m *CreateTargetRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *CreateTargetRequest) GetRule() string {
	if m != nil {
		return m.Rule
	}
	return ""
}

func (m *CreateTargetRequest) GetBRule() string {
	if m != nil {
		return m.BRule
	}
	return ""
}

type CreateTargetResponse struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CreateTargetResponse) Reset()         { *m = CreateTargetResponse{} }
func (m *CreateTargetResponse) String() string { return proto.CompactTextString(m) }
func (*CreateTargetResponse) ProtoMessage()    {}
func (*CreateTargetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{25}
}
func (m *CreateTargetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTargetResponse.Unmarshal(m, b)
}
func (m *CreateTargetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTargetResponse.Marshal(b, m, deterministic)
}
func (m *CreateTargetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTargetResponse.Merge(m, src)
}
func (m *CreateTargetResponse) XXX_Size() int {
	return xxx_messageInfo_CreateTargetResponse.Size(m)
}
func (m *CreateTargetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTargetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTargetResponse proto.InternalMessageInfo

func (m *CreateTargetResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreateTargetResponse) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type ReadTargetRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadTargetRequest) Reset()         { *m = ReadTargetRequest{} }
func (m *ReadTargetRequest) String() string { return proto.CompactTextString(m) }
func (*ReadTargetRequest) ProtoMessage()    {}
func (*ReadTargetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{26}
}
func (m *ReadTargetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadTargetRequest.Unmarshal(m, b)
}
func (m *ReadTargetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadTargetRequest.Marshal(b, m, deterministic)
}
func (m *ReadTargetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadTargetRequest.Merge(m, src)
}
func (m *ReadTargetRequest) XXX_Size() int {
	return xxx_messageInfo_ReadTargetRequest.Size(m)
}
func (m *ReadTargetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadTargetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadTargetRequest proto.InternalMessageInfo

func (m *ReadTargetRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ReadTargetResponse struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	LinkId               string               `protobuf:"bytes,2,opt,name=link_id,json=linkId,proto3" json:"link_id,omitempty"`
	Url                  string               `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Rule                 string               `protobuf:"bytes,4,opt,name=rule,proto3" json:"rule,omitempty"`
	BRule                string               `protobuf:"bytes,5,opt,name=b_rule,json=bRule,proto3" json:"b_rule,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt            *timestamp.Timestamp `protobuf:"bytes,8,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ReadTargetResponse) Reset()         { *m = ReadTargetResponse{} }
func (m *ReadTargetResponse) String() string { return proto.CompactTextString(m) }
func (*ReadTargetResponse) ProtoMessage()    {}
func (*ReadTargetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{27}
}
func (m *ReadTargetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadTargetResponse.Unmarshal(m, b)
}
func (m *ReadTargetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadTargetResponse.Marshal(b, m, deterministic)
}
func (m *ReadTargetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadTargetResponse.Merge(m, src)
}
func (m *ReadTargetResponse) XXX_Size() int {
	return xxx_messageInfo_ReadTargetResponse.Size(m)
}
func (m *ReadTargetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadTargetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadTargetResponse proto.InternalMessageInfo

func (m *ReadTargetResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ReadTargetResponse) GetLinkId() string {
	if m != nil {
		return m.LinkId
	}
	return ""
}

func (m *ReadTargetResponse) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *ReadTargetResponse) GetRule() string {
	if m != nil {
		return m.Rule
	}
	return ""
}

func (m *ReadTargetResponse) GetBRule() string {
	if m != nil {
		return m.BRule
	}
	return ""
}

func (m *ReadTargetResponse) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *ReadTargetResponse) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *ReadTargetResponse) GetDeletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

type UpdateTargetRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	LinkId               string   `protobuf:"bytes,2,opt,name=link_id,json=linkId,proto3" json:"link_id,omitempty"`
	Url                  string   `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Rule                 string   `protobuf:"bytes,4,opt,name=rule,proto3" json:"rule,omitempty"`
	BRule                string   `protobuf:"bytes,5,opt,name=b_rule,json=bRule,proto3" json:"b_rule,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateTargetRequest) Reset()         { *m = UpdateTargetRequest{} }
func (m *UpdateTargetRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateTargetRequest) ProtoMessage()    {}
func (*UpdateTargetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{28}
}
func (m *UpdateTargetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTargetRequest.Unmarshal(m, b)
}
func (m *UpdateTargetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTargetRequest.Marshal(b, m, deterministic)
}
func (m *UpdateTargetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTargetRequest.Merge(m, src)
}
func (m *UpdateTargetRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateTargetRequest.Size(m)
}
func (m *UpdateTargetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTargetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTargetRequest proto.InternalMessageInfo

func (m *UpdateTargetRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateTargetRequest) GetLinkId() string {
	if m != nil {
		return m.LinkId
	}
	return ""
}

func (m *UpdateTargetRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *UpdateTargetRequest) GetRule() string {
	if m != nil {
		return m.Rule
	}
	return ""
}

func (m *UpdateTargetRequest) GetBRule() string {
	if m != nil {
		return m.BRule
	}
	return ""
}

type UpdateTargetResponse struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *UpdateTargetResponse) Reset()         { *m = UpdateTargetResponse{} }
func (m *UpdateTargetResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateTargetResponse) ProtoMessage()    {}
func (*UpdateTargetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{29}
}
func (m *UpdateTargetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTargetResponse.Unmarshal(m, b)
}
func (m *UpdateTargetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTargetResponse.Marshal(b, m, deterministic)
}
func (m *UpdateTargetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTargetResponse.Merge(m, src)
}
func (m *UpdateTargetResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateTargetResponse.Size(m)
}
func (m *UpdateTargetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTargetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTargetResponse proto.InternalMessageInfo

func (m *UpdateTargetResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateTargetResponse) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type DeleteTargetRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteTargetRequest) Reset()         { *m = DeleteTargetRequest{} }
func (m *DeleteTargetRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteTargetRequest) ProtoMessage()    {}
func (*DeleteTargetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{30}
}
func (m *DeleteTargetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteTargetRequest.Unmarshal(m, b)
}
func (m *DeleteTargetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteTargetRequest.Marshal(b, m, deterministic)
}
func (m *DeleteTargetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteTargetRequest.Merge(m, src)
}
func (m *DeleteTargetRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteTargetRequest.Size(m)
}
func (m *DeleteTargetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteTargetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteTargetRequest proto.InternalMessageInfo

func (m *DeleteTargetRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteTargetResponse struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DeletedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *DeleteTargetResponse) Reset()         { *m = DeleteTargetResponse{} }
func (m *DeleteTargetResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteTargetResponse) ProtoMessage()    {}
func (*DeleteTargetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{31}
}
func (m *DeleteTargetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteTargetResponse.Unmarshal(m, b)
}
func (m *DeleteTargetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteTargetResponse.Marshal(b, m, deterministic)
}
func (m *DeleteTargetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteTargetResponse.Merge(m, src)
}
func (m *DeleteTargetResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteTargetResponse.Size(m)
}
func (m *DeleteTargetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteTargetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteTargetResponse proto.InternalMessageInfo

func (m *DeleteTargetResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DeleteTargetResponse) GetDeletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateLinkRequest)(nil), "protobuf.CreateLinkRequest")
	proto.RegisterType((*CreateLinkResponse)(nil), "protobuf.CreateLinkResponse")
	proto.RegisterType((*ReadLinkRequest)(nil), "protobuf.ReadLinkRequest")
	proto.RegisterType((*ReadLinkResponse)(nil), "protobuf.ReadLinkResponse")
	proto.RegisterType((*UpdateLinkRequest)(nil), "protobuf.UpdateLinkRequest")
	proto.RegisterType((*UpdateLinkResponse)(nil), "protobuf.UpdateLinkResponse")
	proto.RegisterType((*DeleteLinkRequest)(nil), "protobuf.DeleteLinkRequest")
	proto.RegisterType((*DeleteLinkResponse)(nil), "protobuf.DeleteLinkResponse")
	proto.RegisterType((*CreateNamespaceRequest)(nil), "protobuf.CreateNamespaceRequest")
	proto.RegisterType((*CreateNamespaceResponse)(nil), "protobuf.CreateNamespaceResponse")
	proto.RegisterType((*ReadNamespaceRequest)(nil), "protobuf.ReadNamespaceRequest")
	proto.RegisterType((*ReadNamespaceResponse)(nil), "protobuf.ReadNamespaceResponse")
	proto.RegisterType((*UpdateNamespaceRequest)(nil), "protobuf.UpdateNamespaceRequest")
	proto.RegisterType((*UpdateNamespaceResponse)(nil), "protobuf.UpdateNamespaceResponse")
	proto.RegisterType((*DeleteNamespaceRequest)(nil), "protobuf.DeleteNamespaceRequest")
	proto.RegisterType((*DeleteNamespaceResponse)(nil), "protobuf.DeleteNamespaceResponse")
	proto.RegisterType((*CreateAliasRequest)(nil), "protobuf.CreateAliasRequest")
	proto.RegisterType((*CreateAliasResponse)(nil), "protobuf.CreateAliasResponse")
	proto.RegisterType((*ReadAliasRequest)(nil), "protobuf.ReadAliasRequest")
	proto.RegisterType((*ReadAliasResponse)(nil), "protobuf.ReadAliasResponse")
	proto.RegisterType((*UpdateAliasRequest)(nil), "protobuf.UpdateAliasRequest")
	proto.RegisterType((*UpdateAliasResponse)(nil), "protobuf.UpdateAliasResponse")
	proto.RegisterType((*DeleteAliasRequest)(nil), "protobuf.DeleteAliasRequest")
	proto.RegisterType((*DeleteAliasResponse)(nil), "protobuf.DeleteAliasResponse")
	proto.RegisterType((*CreateTargetRequest)(nil), "protobuf.CreateTargetRequest")
	proto.RegisterType((*CreateTargetResponse)(nil), "protobuf.CreateTargetResponse")
	proto.RegisterType((*ReadTargetRequest)(nil), "protobuf.ReadTargetRequest")
	proto.RegisterType((*ReadTargetResponse)(nil), "protobuf.ReadTargetResponse")
	proto.RegisterType((*UpdateTargetRequest)(nil), "protobuf.UpdateTargetRequest")
	proto.RegisterType((*UpdateTargetResponse)(nil), "protobuf.UpdateTargetResponse")
	proto.RegisterType((*DeleteTargetRequest)(nil), "protobuf.DeleteTargetRequest")
	proto.RegisterType((*DeleteTargetResponse)(nil), "protobuf.DeleteTargetResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LinkClient is the client API for Link service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LinkClient interface {
	Create(ctx context.Context, in *CreateLinkRequest, opts ...grpc.CallOption) (*CreateLinkResponse, error)
	Read(ctx context.Context, in *ReadLinkRequest, opts ...grpc.CallOption) (*ReadLinkResponse, error)
	Update(ctx context.Context, in *UpdateLinkRequest, opts ...grpc.CallOption) (*UpdateLinkResponse, error)
	Delete(ctx context.Context, in *DeleteLinkRequest, opts ...grpc.CallOption) (*DeleteLinkResponse, error)
}

type linkClient struct {
	cc *grpc.ClientConn
}

func NewLinkClient(cc *grpc.ClientConn) LinkClient {
	return &linkClient{cc}
}

func (c *linkClient) Create(ctx context.Context, in *CreateLinkRequest, opts ...grpc.CallOption) (*CreateLinkResponse, error) {
	out := new(CreateLinkResponse)
	err := c.cc.Invoke(ctx, "/protobuf.Link/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linkClient) Read(ctx context.Context, in *ReadLinkRequest, opts ...grpc.CallOption) (*ReadLinkResponse, error) {
	out := new(ReadLinkResponse)
	err := c.cc.Invoke(ctx, "/protobuf.Link/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linkClient) Update(ctx context.Context, in *UpdateLinkRequest, opts ...grpc.CallOption) (*UpdateLinkResponse, error) {
	out := new(UpdateLinkResponse)
	err := c.cc.Invoke(ctx, "/protobuf.Link/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linkClient) Delete(ctx context.Context, in *DeleteLinkRequest, opts ...grpc.CallOption) (*DeleteLinkResponse, error) {
	out := new(DeleteLinkResponse)
	err := c.cc.Invoke(ctx, "/protobuf.Link/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LinkServer is the server API for Link service.
type LinkServer interface {
	Create(context.Context, *CreateLinkRequest) (*CreateLinkResponse, error)
	Read(context.Context, *ReadLinkRequest) (*ReadLinkResponse, error)
	Update(context.Context, *UpdateLinkRequest) (*UpdateLinkResponse, error)
	Delete(context.Context, *DeleteLinkRequest) (*DeleteLinkResponse, error)
}

func RegisterLinkServer(s *grpc.Server, srv LinkServer) {
	s.RegisterService(&_Link_serviceDesc, srv)
}

func _Link_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinkServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Link/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinkServer).Create(ctx, req.(*CreateLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Link_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinkServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Link/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinkServer).Read(ctx, req.(*ReadLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Link_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinkServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Link/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinkServer).Update(ctx, req.(*UpdateLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Link_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinkServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Link/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinkServer).Delete(ctx, req.(*DeleteLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Link_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.Link",
	HandlerType: (*LinkServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Link_Create_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _Link_Read_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Link_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Link_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "storage.proto",
}

// NamespaceClient is the client API for Namespace service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NamespaceClient interface {
	Create(ctx context.Context, in *CreateNamespaceRequest, opts ...grpc.CallOption) (*CreateNamespaceResponse, error)
	Read(ctx context.Context, in *ReadNamespaceRequest, opts ...grpc.CallOption) (*ReadNamespaceResponse, error)
	Update(ctx context.Context, in *UpdateNamespaceRequest, opts ...grpc.CallOption) (*UpdateNamespaceResponse, error)
	Delete(ctx context.Context, in *DeleteNamespaceRequest, opts ...grpc.CallOption) (*DeleteNamespaceResponse, error)
}

type namespaceClient struct {
	cc *grpc.ClientConn
}

func NewNamespaceClient(cc *grpc.ClientConn) NamespaceClient {
	return &namespaceClient{cc}
}

func (c *namespaceClient) Create(ctx context.Context, in *CreateNamespaceRequest, opts ...grpc.CallOption) (*CreateNamespaceResponse, error) {
	out := new(CreateNamespaceResponse)
	err := c.cc.Invoke(ctx, "/protobuf.Namespace/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *namespaceClient) Read(ctx context.Context, in *ReadNamespaceRequest, opts ...grpc.CallOption) (*ReadNamespaceResponse, error) {
	out := new(ReadNamespaceResponse)
	err := c.cc.Invoke(ctx, "/protobuf.Namespace/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *namespaceClient) Update(ctx context.Context, in *UpdateNamespaceRequest, opts ...grpc.CallOption) (*UpdateNamespaceResponse, error) {
	out := new(UpdateNamespaceResponse)
	err := c.cc.Invoke(ctx, "/protobuf.Namespace/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *namespaceClient) Delete(ctx context.Context, in *DeleteNamespaceRequest, opts ...grpc.CallOption) (*DeleteNamespaceResponse, error) {
	out := new(DeleteNamespaceResponse)
	err := c.cc.Invoke(ctx, "/protobuf.Namespace/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NamespaceServer is the server API for Namespace service.
type NamespaceServer interface {
	Create(context.Context, *CreateNamespaceRequest) (*CreateNamespaceResponse, error)
	Read(context.Context, *ReadNamespaceRequest) (*ReadNamespaceResponse, error)
	Update(context.Context, *UpdateNamespaceRequest) (*UpdateNamespaceResponse, error)
	Delete(context.Context, *DeleteNamespaceRequest) (*DeleteNamespaceResponse, error)
}

func RegisterNamespaceServer(s *grpc.Server, srv NamespaceServer) {
	s.RegisterService(&_Namespace_serviceDesc, srv)
}

func _Namespace_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNamespaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NamespaceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Namespace/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NamespaceServer).Create(ctx, req.(*CreateNamespaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Namespace_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadNamespaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NamespaceServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Namespace/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NamespaceServer).Read(ctx, req.(*ReadNamespaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Namespace_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateNamespaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NamespaceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Namespace/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NamespaceServer).Update(ctx, req.(*UpdateNamespaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Namespace_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteNamespaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NamespaceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Namespace/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NamespaceServer).Delete(ctx, req.(*DeleteNamespaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Namespace_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.Namespace",
	HandlerType: (*NamespaceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Namespace_Create_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _Namespace_Read_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Namespace_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Namespace_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "storage.proto",
}

// AliasClient is the client API for Alias service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AliasClient interface {
	Create(ctx context.Context, in *CreateAliasRequest, opts ...grpc.CallOption) (*CreateAliasResponse, error)
	Read(ctx context.Context, in *ReadAliasRequest, opts ...grpc.CallOption) (*ReadAliasResponse, error)
	Update(ctx context.Context, in *UpdateAliasRequest, opts ...grpc.CallOption) (*UpdateAliasResponse, error)
	Delete(ctx context.Context, in *DeleteAliasRequest, opts ...grpc.CallOption) (*DeleteAliasResponse, error)
}

type aliasClient struct {
	cc *grpc.ClientConn
}

func NewAliasClient(cc *grpc.ClientConn) AliasClient {
	return &aliasClient{cc}
}

func (c *aliasClient) Create(ctx context.Context, in *CreateAliasRequest, opts ...grpc.CallOption) (*CreateAliasResponse, error) {
	out := new(CreateAliasResponse)
	err := c.cc.Invoke(ctx, "/protobuf.Alias/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aliasClient) Read(ctx context.Context, in *ReadAliasRequest, opts ...grpc.CallOption) (*ReadAliasResponse, error) {
	out := new(ReadAliasResponse)
	err := c.cc.Invoke(ctx, "/protobuf.Alias/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aliasClient) Update(ctx context.Context, in *UpdateAliasRequest, opts ...grpc.CallOption) (*UpdateAliasResponse, error) {
	out := new(UpdateAliasResponse)
	err := c.cc.Invoke(ctx, "/protobuf.Alias/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aliasClient) Delete(ctx context.Context, in *DeleteAliasRequest, opts ...grpc.CallOption) (*DeleteAliasResponse, error) {
	out := new(DeleteAliasResponse)
	err := c.cc.Invoke(ctx, "/protobuf.Alias/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AliasServer is the server API for Alias service.
type AliasServer interface {
	Create(context.Context, *CreateAliasRequest) (*CreateAliasResponse, error)
	Read(context.Context, *ReadAliasRequest) (*ReadAliasResponse, error)
	Update(context.Context, *UpdateAliasRequest) (*UpdateAliasResponse, error)
	Delete(context.Context, *DeleteAliasRequest) (*DeleteAliasResponse, error)
}

func RegisterAliasServer(s *grpc.Server, srv AliasServer) {
	s.RegisterService(&_Alias_serviceDesc, srv)
}

func _Alias_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAliasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AliasServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Alias/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AliasServer).Create(ctx, req.(*CreateAliasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Alias_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadAliasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AliasServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Alias/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AliasServer).Read(ctx, req.(*ReadAliasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Alias_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAliasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AliasServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Alias/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AliasServer).Update(ctx, req.(*UpdateAliasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Alias_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAliasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AliasServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Alias/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AliasServer).Delete(ctx, req.(*DeleteAliasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Alias_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.Alias",
	HandlerType: (*AliasServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Alias_Create_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _Alias_Read_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Alias_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Alias_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "storage.proto",
}

// TargetClient is the client API for Target service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TargetClient interface {
	Create(ctx context.Context, in *CreateTargetRequest, opts ...grpc.CallOption) (*CreateTargetResponse, error)
	Read(ctx context.Context, in *ReadTargetRequest, opts ...grpc.CallOption) (*ReadTargetResponse, error)
	Update(ctx context.Context, in *UpdateTargetRequest, opts ...grpc.CallOption) (*UpdateTargetResponse, error)
	Delete(ctx context.Context, in *DeleteTargetRequest, opts ...grpc.CallOption) (*DeleteTargetResponse, error)
}

type targetClient struct {
	cc *grpc.ClientConn
}

func NewTargetClient(cc *grpc.ClientConn) TargetClient {
	return &targetClient{cc}
}

func (c *targetClient) Create(ctx context.Context, in *CreateTargetRequest, opts ...grpc.CallOption) (*CreateTargetResponse, error) {
	out := new(CreateTargetResponse)
	err := c.cc.Invoke(ctx, "/protobuf.Target/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetClient) Read(ctx context.Context, in *ReadTargetRequest, opts ...grpc.CallOption) (*ReadTargetResponse, error) {
	out := new(ReadTargetResponse)
	err := c.cc.Invoke(ctx, "/protobuf.Target/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetClient) Update(ctx context.Context, in *UpdateTargetRequest, opts ...grpc.CallOption) (*UpdateTargetResponse, error) {
	out := new(UpdateTargetResponse)
	err := c.cc.Invoke(ctx, "/protobuf.Target/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetClient) Delete(ctx context.Context, in *DeleteTargetRequest, opts ...grpc.CallOption) (*DeleteTargetResponse, error) {
	out := new(DeleteTargetResponse)
	err := c.cc.Invoke(ctx, "/protobuf.Target/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TargetServer is the server API for Target service.
type TargetServer interface {
	Create(context.Context, *CreateTargetRequest) (*CreateTargetResponse, error)
	Read(context.Context, *ReadTargetRequest) (*ReadTargetResponse, error)
	Update(context.Context, *UpdateTargetRequest) (*UpdateTargetResponse, error)
	Delete(context.Context, *DeleteTargetRequest) (*DeleteTargetResponse, error)
}

func RegisterTargetServer(s *grpc.Server, srv TargetServer) {
	s.RegisterService(&_Target_serviceDesc, srv)
}

func _Target_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTargetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Target/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetServer).Create(ctx, req.(*CreateTargetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Target_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadTargetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Target/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetServer).Read(ctx, req.(*ReadTargetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Target_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTargetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Target/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetServer).Update(ctx, req.(*UpdateTargetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Target_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTargetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Target/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetServer).Delete(ctx, req.(*DeleteTargetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Target_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.Target",
	HandlerType: (*TargetServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Target_Create_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _Target_Read_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Target_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Target_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "storage.proto",
}

func init() { proto.RegisterFile("storage.proto", fileDescriptor_0d2c4ccf1453ffdb) }

var fileDescriptor_0d2c4ccf1453ffdb = []byte{
	// 820 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x57, 0xcd, 0x4e, 0xdb, 0x4a,
	0x18, 0x4d, 0x4c, 0x62, 0xc8, 0x07, 0xf7, 0x5e, 0x18, 0x7e, 0xaf, 0xe1, 0x42, 0x18, 0x6e, 0x2b,
	0x56, 0x41, 0x4a, 0x17, 0x55, 0x25, 0xa4, 0x2a, 0xa2, 0x08, 0x45, 0xaa, 0x4a, 0x15, 0xd1, 0x75,
	0x70, 0xf0, 0x34, 0xb2, 0x70, 0xec, 0xd4, 0x76, 0x56, 0x7d, 0x95, 0xae, 0x2a, 0x75, 0x55, 0xa9,
	0xef, 0xd1, 0x27, 0xe9, 0xa6, 0x0f, 0x51, 0x79, 0xc6, 0x1e, 0xc6, 0x1e, 0x8f, 0x23, 0xa7, 0x56,
	0x2b, 0x75, 0x85, 0xf1, 0xf7, 0xe3, 0x33, 0x67, 0xce, 0x99, 0xf9, 0x02, 0x7f, 0x05, 0xa1, 0xe7,
	0x9b, 0x63, 0xd2, 0x99, 0xfa, 0x5e, 0xe8, 0xa1, 0x15, 0xfa, 0x67, 0x34, 0x7b, 0x6b, 0xac, 0xdd,
	0x79, 0x93, 0x89, 0xe7, 0xb2, 0xf7, 0xc6, 0xd1, 0xd8, 0xf3, 0xc6, 0x0e, 0x39, 0x4b, 0xc2, 0x67,
	0xa1, 0x3d, 0x21, 0x41, 0x68, 0x4e, 0xa6, 0x2c, 0x01, 0x3f, 0x85, 0x8d, 0x0b, 0x9f, 0x98, 0x21,
	0x79, 0x69, 0xbb, 0xf7, 0x03, 0xf2, 0x6e, 0x46, 0x82, 0x10, 0xfd, 0x0d, 0x9a, 0x6d, 0xed, 0xd5,
	0xdb, 0xf5, 0xd3, 0xd6, 0x40, 0xb3, 0x2d, 0x84, 0xa0, 0xe1, 0x9a, 0x13, 0xb2, 0xa7, 0xd1, 0x37,
	0xf4, 0x19, 0x0f, 0x01, 0x89, 0x85, 0xc1, 0xd4, 0x73, 0x03, 0x22, 0x55, 0x3e, 0x03, 0xb8, 0xa3,
	0x59, 0xd6, 0xd0, 0x0c, 0x69, 0xfd, 0x6a, 0xd7, 0xe8, 0x30, 0x50, 0x9d, 0x04, 0x54, 0xe7, 0x26,
	0x01, 0x35, 0x68, 0xc5, 0xd9, 0xbd, 0x10, 0x1f, 0xc3, 0x3f, 0x03, 0x62, 0x5a, 0x05, 0xb8, 0xf0,
	0xb7, 0x3a, 0xac, 0x3f, 0xe4, 0x28, 0x20, 0xe4, 0x80, 0xcf, 0xc0, 0x5a, 0x2a, 0x01, 0x2b, 0x2a,
	0x9d, 0x4d, 0xad, 0xa4, 0xb4, 0x31, 0xbf, 0x34, 0xce, 0x66, 0xa5, 0x16, 0x71, 0x48, 0x5c, 0xda,
	0x9c, 0x5f, 0x1a, 0x67, 0xf7, 0xc2, 0x68, 0x9b, 0xde, 0xd0, 0x3e, 0x0b, 0x6c, 0x93, 0x58, 0xa8,
	0xde, 0x26, 0x61, 0x51, 0x5a, 0x89, 0x45, 0xe1, 0x13, 0xd8, 0x78, 0x41, 0x61, 0x16, 0x6d, 0xd4,
	0x10, 0x90, 0x98, 0xa4, 0x46, 0x21, 0xf0, 0xa3, 0x95, 0xe1, 0xe7, 0x1c, 0x76, 0x98, 0x1a, 0x5f,
	0x99, 0x13, 0x12, 0x4c, 0xcd, 0x3b, 0x52, 0x86, 0x24, 0x0b, 0x76, 0xa5, 0xea, 0xea, 0x05, 0xfd,
	0x18, 0xb6, 0x22, 0xb1, 0xce, 0x43, 0x88, 0xbf, 0xd7, 0x61, 0x3b, 0x93, 0xf8, 0x27, 0x4b, 0xfb,
	0x1c, 0x76, 0x98, 0x42, 0x17, 0xdd, 0x3a, 0xa9, 0xba, 0x7a, 0x91, 0x9f, 0xc2, 0x0e, 0xd3, 0xef,
	0xdc, 0xcd, 0xb3, 0x60, 0x57, 0xca, 0xac, 0x5e, 0xee, 0x7e, 0x72, 0xf8, 0xf6, 0x1c, 0xdb, 0x0c,
	0x54, 0x7c, 0xed, 0xc2, 0xb2, 0x63, 0xbb, 0xf7, 0x43, 0xdb, 0x8a, 0x29, 0xd3, 0xa3, 0x7f, 0xfb,
	0x16, 0x3a, 0x86, 0x35, 0x37, 0x81, 0x17, 0x45, 0x97, 0x68, 0x74, 0x95, 0xbf, 0xeb, 0x5b, 0x68,
	0x1d, 0x96, 0x66, 0xbe, 0x4b, 0x45, 0xd0, 0x1a, 0x44, 0x8f, 0xf8, 0x16, 0x36, 0x53, 0xdf, 0xac,
	0xde, 0x20, 0x98, 0x9d, 0xe6, 0x45, 0x6b, 0xc2, 0x1f, 0x35, 0xd8, 0x10, 0x92, 0x14, 0x20, 0x2a,
	0x5d, 0x79, 0x66, 0x49, 0xcd, 0xc5, 0x2d, 0xa5, 0x2f, 0x6e, 0xa9, 0xe5, 0x92, 0xf2, 0x60, 0xa6,
	0xf8, 0xb5, 0xf2, 0x48, 0x7d, 0xb3, 0x7a, 0x13, 0xfe, 0x9f, 0x5c, 0x22, 0x85, 0x02, 0xb9, 0x85,
	0xcd, 0x54, 0x56, 0xf5, 0xe6, 0x7b, 0x9f, 0x18, 0xe1, 0xc6, 0xf4, 0xc7, 0x24, 0x2c, 0x4d, 0x2f,
	0xe5, 0xce, 0x89, 0x59, 0x8d, 0x1e, 0xa3, 0x83, 0xcd, 0x9f, 0x39, 0x24, 0xa6, 0x93, 0x3e, 0xa3,
	0x6d, 0xd0, 0x47, 0x43, 0xfa, 0xb6, 0x49, 0xdf, 0x36, 0x47, 0x83, 0x99, 0x43, 0xb0, 0x09, 0x5b,
	0xe9, 0x8f, 0x57, 0x6f, 0xc3, 0x13, 0xe6, 0xb0, 0xc2, 0xd5, 0xe1, 0xcf, 0x1a, 0x20, 0x31, 0xab,
	0xac, 0x11, 0x7f, 0x86, 0x84, 0xcc, 0xe2, 0xf4, 0xc5, 0x0d, 0xb9, 0xbc, 0xb8, 0x21, 0x57, 0x4a,
	0x4a, 0x86, 0x99, 0xe3, 0x37, 0x49, 0x26, 0xfd, 0xf1, 0xea, 0xad, 0xf9, 0x28, 0x31, 0x5d, 0xb1,
	0x68, 0x4c, 0xd8, 0x4a, 0xa7, 0x55, 0x6e, 0xce, 0xee, 0x07, 0x0d, 0x1a, 0xd1, 0x90, 0x89, 0x2e,
	0x41, 0x67, 0x46, 0x41, 0xfb, 0x0f, 0x25, 0xd2, 0x4f, 0x1d, 0xe3, 0x20, 0x3f, 0xc8, 0x80, 0xe1,
	0x1a, 0x7a, 0x0e, 0x8d, 0x48, 0xe6, 0xe8, 0xdf, 0x87, 0xbc, 0xcc, 0xaf, 0x12, 0xc3, 0xc8, 0x0b,
	0xf1, 0x06, 0x97, 0xa0, 0x33, 0xf6, 0x45, 0x1c, 0xd2, 0x2c, 0x2f, 0xe2, 0x90, 0xe7, 0x75, 0xd6,
	0x86, 0x51, 0x27, 0xb6, 0x91, 0x06, 0x6f, 0xb1, 0x8d, 0x3c, 0x70, 0xe3, 0x5a, 0xf7, 0xab, 0x06,
	0x2d, 0x3e, 0x99, 0xa0, 0x6b, 0xce, 0x51, 0x3b, 0x4b, 0x43, 0x76, 0xd0, 0x31, 0x8e, 0x0b, 0x32,
	0x38, 0xca, 0x7e, 0xcc, 0xd6, 0x61, 0x9a, 0x12, 0xa9, 0xd9, 0x91, 0x32, 0xce, 0x5b, 0x5d, 0x73,
	0xde, 0xda, 0x59, 0x6a, 0x8a, 0xb0, 0x29, 0x86, 0x41, 0xd6, 0x30, 0x66, 0xb0, 0x9d, 0x25, 0xa9,
	0xa8, 0xa1, 0x62, 0x9a, 0xc3, 0xb5, 0xee, 0x27, 0x0d, 0x9a, 0xf4, 0x92, 0x41, 0x57, 0x9c, 0x47,
	0x49, 0x4e, 0xe2, 0x5d, 0x65, 0xfc, 0xa7, 0x88, 0x72, 0x8c, 0xbd, 0x98, 0xbf, 0x8c, 0xa4, 0x52,
	0x4d, 0xf6, 0x73, 0x63, 0xbc, 0xc5, 0x15, 0xe7, 0x4d, 0x92, 0x94, 0x0a, 0x4b, 0xce, 0xbd, 0xcd,
	0x1a, 0xc5, 0x7c, 0x49, 0xa2, 0x52, 0x35, 0xca, 0xb9, 0x78, 0x71, 0xad, 0xfb, 0x45, 0x03, 0x9d,
	0x19, 0x1e, 0xf5, 0x39, 0x51, 0x12, 0x15, 0xa9, 0x93, 0xc3, 0x38, 0x54, 0x85, 0x39, 0xbc, 0x8b,
	0x98, 0xaa, 0x0c, 0x1d, 0xe9, 0x36, 0x07, 0xf9, 0x41, 0x41, 0xaf, 0x09, 0x59, 0x12, 0x1d, 0x4a,
	0x3c, 0x79, 0x67, 0x29, 0x6b, 0x15, 0xd3, 0x25, 0x11, 0xa2, 0x6c, 0x95, 0x77, 0x18, 0xe2, 0xda,
	0xeb, 0xda, 0x48, 0xa7, 0x29, 0x4f, 0x7e, 0x04, 0x00, 0x00, 0xff, 0xff, 0x89, 0x36, 0xd3, 0x3b,
	0xe6, 0x11, 0x00, 0x00,
}
