TRUNCATE TABLE "link" RESTART IDENTITY RESTRICT;
TRUNCATE TABLE "namespace" RESTART IDENTITY RESTRICT;
TRUNCATE TABLE "alias" RESTART IDENTITY RESTRICT;
TRUNCATE TABLE "target" RESTART IDENTITY RESTRICT;
TRUNCATE TABLE "event" RESTART IDENTITY RESTRICT;
