// Code generated by protoc-gen-go. DO NOT EDIT.
// source: storage.proto

package grpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateNamespaceRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateNamespaceRequest) Reset()         { *m = CreateNamespaceRequest{} }
func (m *CreateNamespaceRequest) String() string { return proto.CompactTextString(m) }
func (*CreateNamespaceRequest) ProtoMessage()    {}
func (*CreateNamespaceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_66e1adc07c3c018b, []int{0}
}
func (m *CreateNamespaceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateNamespaceRequest.Unmarshal(m, b)
}
func (m *CreateNamespaceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateNamespaceRequest.Marshal(b, m, deterministic)
}
func (dst *CreateNamespaceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateNamespaceRequest.Merge(dst, src)
}
func (m *CreateNamespaceRequest) XXX_Size() int {
	return xxx_messageInfo_CreateNamespaceRequest.Size(m)
}
func (m *CreateNamespaceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateNamespaceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateNamespaceRequest proto.InternalMessageInfo

type CreateNamespaceResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateNamespaceResponse) Reset()         { *m = CreateNamespaceResponse{} }
func (m *CreateNamespaceResponse) String() string { return proto.CompactTextString(m) }
func (*CreateNamespaceResponse) ProtoMessage()    {}
func (*CreateNamespaceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_66e1adc07c3c018b, []int{1}
}
func (m *CreateNamespaceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateNamespaceResponse.Unmarshal(m, b)
}
func (m *CreateNamespaceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateNamespaceResponse.Marshal(b, m, deterministic)
}
func (dst *CreateNamespaceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateNamespaceResponse.Merge(dst, src)
}
func (m *CreateNamespaceResponse) XXX_Size() int {
	return xxx_messageInfo_CreateNamespaceResponse.Size(m)
}
func (m *CreateNamespaceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateNamespaceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateNamespaceResponse proto.InternalMessageInfo

type ReadNamespaceRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadNamespaceRequest) Reset()         { *m = ReadNamespaceRequest{} }
func (m *ReadNamespaceRequest) String() string { return proto.CompactTextString(m) }
func (*ReadNamespaceRequest) ProtoMessage()    {}
func (*ReadNamespaceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_66e1adc07c3c018b, []int{2}
}
func (m *ReadNamespaceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadNamespaceRequest.Unmarshal(m, b)
}
func (m *ReadNamespaceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadNamespaceRequest.Marshal(b, m, deterministic)
}
func (dst *ReadNamespaceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadNamespaceRequest.Merge(dst, src)
}
func (m *ReadNamespaceRequest) XXX_Size() int {
	return xxx_messageInfo_ReadNamespaceRequest.Size(m)
}
func (m *ReadNamespaceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadNamespaceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadNamespaceRequest proto.InternalMessageInfo

type ReadNamespaceResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadNamespaceResponse) Reset()         { *m = ReadNamespaceResponse{} }
func (m *ReadNamespaceResponse) String() string { return proto.CompactTextString(m) }
func (*ReadNamespaceResponse) ProtoMessage()    {}
func (*ReadNamespaceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_66e1adc07c3c018b, []int{3}
}
func (m *ReadNamespaceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadNamespaceResponse.Unmarshal(m, b)
}
func (m *ReadNamespaceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadNamespaceResponse.Marshal(b, m, deterministic)
}
func (dst *ReadNamespaceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadNamespaceResponse.Merge(dst, src)
}
func (m *ReadNamespaceResponse) XXX_Size() int {
	return xxx_messageInfo_ReadNamespaceResponse.Size(m)
}
func (m *ReadNamespaceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadNamespaceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadNamespaceResponse proto.InternalMessageInfo

type UpdateNamespaceRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateNamespaceRequest) Reset()         { *m = UpdateNamespaceRequest{} }
func (m *UpdateNamespaceRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateNamespaceRequest) ProtoMessage()    {}
func (*UpdateNamespaceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_66e1adc07c3c018b, []int{4}
}
func (m *UpdateNamespaceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateNamespaceRequest.Unmarshal(m, b)
}
func (m *UpdateNamespaceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateNamespaceRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateNamespaceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateNamespaceRequest.Merge(dst, src)
}
func (m *UpdateNamespaceRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateNamespaceRequest.Size(m)
}
func (m *UpdateNamespaceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateNamespaceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateNamespaceRequest proto.InternalMessageInfo

type UpdateNamespaceResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateNamespaceResponse) Reset()         { *m = UpdateNamespaceResponse{} }
func (m *UpdateNamespaceResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateNamespaceResponse) ProtoMessage()    {}
func (*UpdateNamespaceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_66e1adc07c3c018b, []int{5}
}
func (m *UpdateNamespaceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateNamespaceResponse.Unmarshal(m, b)
}
func (m *UpdateNamespaceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateNamespaceResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateNamespaceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateNamespaceResponse.Merge(dst, src)
}
func (m *UpdateNamespaceResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateNamespaceResponse.Size(m)
}
func (m *UpdateNamespaceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateNamespaceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateNamespaceResponse proto.InternalMessageInfo

type DeleteNamespaceRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteNamespaceRequest) Reset()         { *m = DeleteNamespaceRequest{} }
func (m *DeleteNamespaceRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteNamespaceRequest) ProtoMessage()    {}
func (*DeleteNamespaceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_66e1adc07c3c018b, []int{6}
}
func (m *DeleteNamespaceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteNamespaceRequest.Unmarshal(m, b)
}
func (m *DeleteNamespaceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteNamespaceRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteNamespaceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteNamespaceRequest.Merge(dst, src)
}
func (m *DeleteNamespaceRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteNamespaceRequest.Size(m)
}
func (m *DeleteNamespaceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteNamespaceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteNamespaceRequest proto.InternalMessageInfo

type DeleteNamespaceResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteNamespaceResponse) Reset()         { *m = DeleteNamespaceResponse{} }
func (m *DeleteNamespaceResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteNamespaceResponse) ProtoMessage()    {}
func (*DeleteNamespaceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_66e1adc07c3c018b, []int{7}
}
func (m *DeleteNamespaceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteNamespaceResponse.Unmarshal(m, b)
}
func (m *DeleteNamespaceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteNamespaceResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteNamespaceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteNamespaceResponse.Merge(dst, src)
}
func (m *DeleteNamespaceResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteNamespaceResponse.Size(m)
}
func (m *DeleteNamespaceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteNamespaceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteNamespaceResponse proto.InternalMessageInfo

type CreateLinkRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateLinkRequest) Reset()         { *m = CreateLinkRequest{} }
func (m *CreateLinkRequest) String() string { return proto.CompactTextString(m) }
func (*CreateLinkRequest) ProtoMessage()    {}
func (*CreateLinkRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_66e1adc07c3c018b, []int{8}
}
func (m *CreateLinkRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateLinkRequest.Unmarshal(m, b)
}
func (m *CreateLinkRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateLinkRequest.Marshal(b, m, deterministic)
}
func (dst *CreateLinkRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateLinkRequest.Merge(dst, src)
}
func (m *CreateLinkRequest) XXX_Size() int {
	return xxx_messageInfo_CreateLinkRequest.Size(m)
}
func (m *CreateLinkRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateLinkRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateLinkRequest proto.InternalMessageInfo

type CreateLinkResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateLinkResponse) Reset()         { *m = CreateLinkResponse{} }
func (m *CreateLinkResponse) String() string { return proto.CompactTextString(m) }
func (*CreateLinkResponse) ProtoMessage()    {}
func (*CreateLinkResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_66e1adc07c3c018b, []int{9}
}
func (m *CreateLinkResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateLinkResponse.Unmarshal(m, b)
}
func (m *CreateLinkResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateLinkResponse.Marshal(b, m, deterministic)
}
func (dst *CreateLinkResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateLinkResponse.Merge(dst, src)
}
func (m *CreateLinkResponse) XXX_Size() int {
	return xxx_messageInfo_CreateLinkResponse.Size(m)
}
func (m *CreateLinkResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateLinkResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateLinkResponse proto.InternalMessageInfo

type ReadLinkRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadLinkRequest) Reset()         { *m = ReadLinkRequest{} }
func (m *ReadLinkRequest) String() string { return proto.CompactTextString(m) }
func (*ReadLinkRequest) ProtoMessage()    {}
func (*ReadLinkRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_66e1adc07c3c018b, []int{10}
}
func (m *ReadLinkRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadLinkRequest.Unmarshal(m, b)
}
func (m *ReadLinkRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadLinkRequest.Marshal(b, m, deterministic)
}
func (dst *ReadLinkRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadLinkRequest.Merge(dst, src)
}
func (m *ReadLinkRequest) XXX_Size() int {
	return xxx_messageInfo_ReadLinkRequest.Size(m)
}
func (m *ReadLinkRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadLinkRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadLinkRequest proto.InternalMessageInfo

type ReadLinkResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadLinkResponse) Reset()         { *m = ReadLinkResponse{} }
func (m *ReadLinkResponse) String() string { return proto.CompactTextString(m) }
func (*ReadLinkResponse) ProtoMessage()    {}
func (*ReadLinkResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_66e1adc07c3c018b, []int{11}
}
func (m *ReadLinkResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadLinkResponse.Unmarshal(m, b)
}
func (m *ReadLinkResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadLinkResponse.Marshal(b, m, deterministic)
}
func (dst *ReadLinkResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadLinkResponse.Merge(dst, src)
}
func (m *ReadLinkResponse) XXX_Size() int {
	return xxx_messageInfo_ReadLinkResponse.Size(m)
}
func (m *ReadLinkResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadLinkResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadLinkResponse proto.InternalMessageInfo

type UpdateLinkRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateLinkRequest) Reset()         { *m = UpdateLinkRequest{} }
func (m *UpdateLinkRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateLinkRequest) ProtoMessage()    {}
func (*UpdateLinkRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_66e1adc07c3c018b, []int{12}
}
func (m *UpdateLinkRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateLinkRequest.Unmarshal(m, b)
}
func (m *UpdateLinkRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateLinkRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateLinkRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateLinkRequest.Merge(dst, src)
}
func (m *UpdateLinkRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateLinkRequest.Size(m)
}
func (m *UpdateLinkRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateLinkRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateLinkRequest proto.InternalMessageInfo

type UpdateLinkResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateLinkResponse) Reset()         { *m = UpdateLinkResponse{} }
func (m *UpdateLinkResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateLinkResponse) ProtoMessage()    {}
func (*UpdateLinkResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_66e1adc07c3c018b, []int{13}
}
func (m *UpdateLinkResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateLinkResponse.Unmarshal(m, b)
}
func (m *UpdateLinkResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateLinkResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateLinkResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateLinkResponse.Merge(dst, src)
}
func (m *UpdateLinkResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateLinkResponse.Size(m)
}
func (m *UpdateLinkResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateLinkResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateLinkResponse proto.InternalMessageInfo

type DeleteLinkRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteLinkRequest) Reset()         { *m = DeleteLinkRequest{} }
func (m *DeleteLinkRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteLinkRequest) ProtoMessage()    {}
func (*DeleteLinkRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_66e1adc07c3c018b, []int{14}
}
func (m *DeleteLinkRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteLinkRequest.Unmarshal(m, b)
}
func (m *DeleteLinkRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteLinkRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteLinkRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteLinkRequest.Merge(dst, src)
}
func (m *DeleteLinkRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteLinkRequest.Size(m)
}
func (m *DeleteLinkRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteLinkRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteLinkRequest proto.InternalMessageInfo

type DeleteLinkResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteLinkResponse) Reset()         { *m = DeleteLinkResponse{} }
func (m *DeleteLinkResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteLinkResponse) ProtoMessage()    {}
func (*DeleteLinkResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_66e1adc07c3c018b, []int{15}
}
func (m *DeleteLinkResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteLinkResponse.Unmarshal(m, b)
}
func (m *DeleteLinkResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteLinkResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteLinkResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteLinkResponse.Merge(dst, src)
}
func (m *DeleteLinkResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteLinkResponse.Size(m)
}
func (m *DeleteLinkResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteLinkResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteLinkResponse proto.InternalMessageInfo

type CreateAliasRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAliasRequest) Reset()         { *m = CreateAliasRequest{} }
func (m *CreateAliasRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAliasRequest) ProtoMessage()    {}
func (*CreateAliasRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_66e1adc07c3c018b, []int{16}
}
func (m *CreateAliasRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAliasRequest.Unmarshal(m, b)
}
func (m *CreateAliasRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAliasRequest.Marshal(b, m, deterministic)
}
func (dst *CreateAliasRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAliasRequest.Merge(dst, src)
}
func (m *CreateAliasRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAliasRequest.Size(m)
}
func (m *CreateAliasRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAliasRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAliasRequest proto.InternalMessageInfo

type CreateAliasResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAliasResponse) Reset()         { *m = CreateAliasResponse{} }
func (m *CreateAliasResponse) String() string { return proto.CompactTextString(m) }
func (*CreateAliasResponse) ProtoMessage()    {}
func (*CreateAliasResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_66e1adc07c3c018b, []int{17}
}
func (m *CreateAliasResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAliasResponse.Unmarshal(m, b)
}
func (m *CreateAliasResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAliasResponse.Marshal(b, m, deterministic)
}
func (dst *CreateAliasResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAliasResponse.Merge(dst, src)
}
func (m *CreateAliasResponse) XXX_Size() int {
	return xxx_messageInfo_CreateAliasResponse.Size(m)
}
func (m *CreateAliasResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAliasResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAliasResponse proto.InternalMessageInfo

type ReadAliasRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadAliasRequest) Reset()         { *m = ReadAliasRequest{} }
func (m *ReadAliasRequest) String() string { return proto.CompactTextString(m) }
func (*ReadAliasRequest) ProtoMessage()    {}
func (*ReadAliasRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_66e1adc07c3c018b, []int{18}
}
func (m *ReadAliasRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadAliasRequest.Unmarshal(m, b)
}
func (m *ReadAliasRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadAliasRequest.Marshal(b, m, deterministic)
}
func (dst *ReadAliasRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadAliasRequest.Merge(dst, src)
}
func (m *ReadAliasRequest) XXX_Size() int {
	return xxx_messageInfo_ReadAliasRequest.Size(m)
}
func (m *ReadAliasRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadAliasRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadAliasRequest proto.InternalMessageInfo

type ReadAliasResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadAliasResponse) Reset()         { *m = ReadAliasResponse{} }
func (m *ReadAliasResponse) String() string { return proto.CompactTextString(m) }
func (*ReadAliasResponse) ProtoMessage()    {}
func (*ReadAliasResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_66e1adc07c3c018b, []int{19}
}
func (m *ReadAliasResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadAliasResponse.Unmarshal(m, b)
}
func (m *ReadAliasResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadAliasResponse.Marshal(b, m, deterministic)
}
func (dst *ReadAliasResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadAliasResponse.Merge(dst, src)
}
func (m *ReadAliasResponse) XXX_Size() int {
	return xxx_messageInfo_ReadAliasResponse.Size(m)
}
func (m *ReadAliasResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadAliasResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadAliasResponse proto.InternalMessageInfo

type UpdateAliasRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateAliasRequest) Reset()         { *m = UpdateAliasRequest{} }
func (m *UpdateAliasRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateAliasRequest) ProtoMessage()    {}
func (*UpdateAliasRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_66e1adc07c3c018b, []int{20}
}
func (m *UpdateAliasRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAliasRequest.Unmarshal(m, b)
}
func (m *UpdateAliasRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAliasRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateAliasRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAliasRequest.Merge(dst, src)
}
func (m *UpdateAliasRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateAliasRequest.Size(m)
}
func (m *UpdateAliasRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAliasRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAliasRequest proto.InternalMessageInfo

type UpdateAliasResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateAliasResponse) Reset()         { *m = UpdateAliasResponse{} }
func (m *UpdateAliasResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateAliasResponse) ProtoMessage()    {}
func (*UpdateAliasResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_66e1adc07c3c018b, []int{21}
}
func (m *UpdateAliasResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAliasResponse.Unmarshal(m, b)
}
func (m *UpdateAliasResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAliasResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateAliasResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAliasResponse.Merge(dst, src)
}
func (m *UpdateAliasResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateAliasResponse.Size(m)
}
func (m *UpdateAliasResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAliasResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAliasResponse proto.InternalMessageInfo

type DeleteAliasRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAliasRequest) Reset()         { *m = DeleteAliasRequest{} }
func (m *DeleteAliasRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteAliasRequest) ProtoMessage()    {}
func (*DeleteAliasRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_66e1adc07c3c018b, []int{22}
}
func (m *DeleteAliasRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAliasRequest.Unmarshal(m, b)
}
func (m *DeleteAliasRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAliasRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteAliasRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAliasRequest.Merge(dst, src)
}
func (m *DeleteAliasRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteAliasRequest.Size(m)
}
func (m *DeleteAliasRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAliasRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAliasRequest proto.InternalMessageInfo

type DeleteAliasResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAliasResponse) Reset()         { *m = DeleteAliasResponse{} }
func (m *DeleteAliasResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteAliasResponse) ProtoMessage()    {}
func (*DeleteAliasResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_66e1adc07c3c018b, []int{23}
}
func (m *DeleteAliasResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAliasResponse.Unmarshal(m, b)
}
func (m *DeleteAliasResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAliasResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteAliasResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAliasResponse.Merge(dst, src)
}
func (m *DeleteAliasResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteAliasResponse.Size(m)
}
func (m *DeleteAliasResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAliasResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAliasResponse proto.InternalMessageInfo

type CreateTargetRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTargetRequest) Reset()         { *m = CreateTargetRequest{} }
func (m *CreateTargetRequest) String() string { return proto.CompactTextString(m) }
func (*CreateTargetRequest) ProtoMessage()    {}
func (*CreateTargetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_66e1adc07c3c018b, []int{24}
}
func (m *CreateTargetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTargetRequest.Unmarshal(m, b)
}
func (m *CreateTargetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTargetRequest.Marshal(b, m, deterministic)
}
func (dst *CreateTargetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTargetRequest.Merge(dst, src)
}
func (m *CreateTargetRequest) XXX_Size() int {
	return xxx_messageInfo_CreateTargetRequest.Size(m)
}
func (m *CreateTargetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTargetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTargetRequest proto.InternalMessageInfo

type CreateTargetResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTargetResponse) Reset()         { *m = CreateTargetResponse{} }
func (m *CreateTargetResponse) String() string { return proto.CompactTextString(m) }
func (*CreateTargetResponse) ProtoMessage()    {}
func (*CreateTargetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_66e1adc07c3c018b, []int{25}
}
func (m *CreateTargetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTargetResponse.Unmarshal(m, b)
}
func (m *CreateTargetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTargetResponse.Marshal(b, m, deterministic)
}
func (dst *CreateTargetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTargetResponse.Merge(dst, src)
}
func (m *CreateTargetResponse) XXX_Size() int {
	return xxx_messageInfo_CreateTargetResponse.Size(m)
}
func (m *CreateTargetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTargetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTargetResponse proto.InternalMessageInfo

type ReadTargetRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadTargetRequest) Reset()         { *m = ReadTargetRequest{} }
func (m *ReadTargetRequest) String() string { return proto.CompactTextString(m) }
func (*ReadTargetRequest) ProtoMessage()    {}
func (*ReadTargetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_66e1adc07c3c018b, []int{26}
}
func (m *ReadTargetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadTargetRequest.Unmarshal(m, b)
}
func (m *ReadTargetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadTargetRequest.Marshal(b, m, deterministic)
}
func (dst *ReadTargetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadTargetRequest.Merge(dst, src)
}
func (m *ReadTargetRequest) XXX_Size() int {
	return xxx_messageInfo_ReadTargetRequest.Size(m)
}
func (m *ReadTargetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadTargetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadTargetRequest proto.InternalMessageInfo

type ReadTargetResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadTargetResponse) Reset()         { *m = ReadTargetResponse{} }
func (m *ReadTargetResponse) String() string { return proto.CompactTextString(m) }
func (*ReadTargetResponse) ProtoMessage()    {}
func (*ReadTargetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_66e1adc07c3c018b, []int{27}
}
func (m *ReadTargetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadTargetResponse.Unmarshal(m, b)
}
func (m *ReadTargetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadTargetResponse.Marshal(b, m, deterministic)
}
func (dst *ReadTargetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadTargetResponse.Merge(dst, src)
}
func (m *ReadTargetResponse) XXX_Size() int {
	return xxx_messageInfo_ReadTargetResponse.Size(m)
}
func (m *ReadTargetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadTargetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadTargetResponse proto.InternalMessageInfo

type UpdateTargetRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateTargetRequest) Reset()         { *m = UpdateTargetRequest{} }
func (m *UpdateTargetRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateTargetRequest) ProtoMessage()    {}
func (*UpdateTargetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_66e1adc07c3c018b, []int{28}
}
func (m *UpdateTargetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTargetRequest.Unmarshal(m, b)
}
func (m *UpdateTargetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTargetRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateTargetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTargetRequest.Merge(dst, src)
}
func (m *UpdateTargetRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateTargetRequest.Size(m)
}
func (m *UpdateTargetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTargetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTargetRequest proto.InternalMessageInfo

type UpdateTargetResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateTargetResponse) Reset()         { *m = UpdateTargetResponse{} }
func (m *UpdateTargetResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateTargetResponse) ProtoMessage()    {}
func (*UpdateTargetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_66e1adc07c3c018b, []int{29}
}
func (m *UpdateTargetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTargetResponse.Unmarshal(m, b)
}
func (m *UpdateTargetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTargetResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateTargetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTargetResponse.Merge(dst, src)
}
func (m *UpdateTargetResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateTargetResponse.Size(m)
}
func (m *UpdateTargetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTargetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTargetResponse proto.InternalMessageInfo

type DeleteTargetRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteTargetRequest) Reset()         { *m = DeleteTargetRequest{} }
func (m *DeleteTargetRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteTargetRequest) ProtoMessage()    {}
func (*DeleteTargetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_66e1adc07c3c018b, []int{30}
}
func (m *DeleteTargetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteTargetRequest.Unmarshal(m, b)
}
func (m *DeleteTargetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteTargetRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteTargetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteTargetRequest.Merge(dst, src)
}
func (m *DeleteTargetRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteTargetRequest.Size(m)
}
func (m *DeleteTargetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteTargetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteTargetRequest proto.InternalMessageInfo

type DeleteTargetResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteTargetResponse) Reset()         { *m = DeleteTargetResponse{} }
func (m *DeleteTargetResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteTargetResponse) ProtoMessage()    {}
func (*DeleteTargetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_66e1adc07c3c018b, []int{31}
}
func (m *DeleteTargetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteTargetResponse.Unmarshal(m, b)
}
func (m *DeleteTargetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteTargetResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteTargetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteTargetResponse.Merge(dst, src)
}
func (m *DeleteTargetResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteTargetResponse.Size(m)
}
func (m *DeleteTargetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteTargetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteTargetResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*CreateNamespaceRequest)(nil), "grpc.CreateNamespaceRequest")
	proto.RegisterType((*CreateNamespaceResponse)(nil), "grpc.CreateNamespaceResponse")
	proto.RegisterType((*ReadNamespaceRequest)(nil), "grpc.ReadNamespaceRequest")
	proto.RegisterType((*ReadNamespaceResponse)(nil), "grpc.ReadNamespaceResponse")
	proto.RegisterType((*UpdateNamespaceRequest)(nil), "grpc.UpdateNamespaceRequest")
	proto.RegisterType((*UpdateNamespaceResponse)(nil), "grpc.UpdateNamespaceResponse")
	proto.RegisterType((*DeleteNamespaceRequest)(nil), "grpc.DeleteNamespaceRequest")
	proto.RegisterType((*DeleteNamespaceResponse)(nil), "grpc.DeleteNamespaceResponse")
	proto.RegisterType((*CreateLinkRequest)(nil), "grpc.CreateLinkRequest")
	proto.RegisterType((*CreateLinkResponse)(nil), "grpc.CreateLinkResponse")
	proto.RegisterType((*ReadLinkRequest)(nil), "grpc.ReadLinkRequest")
	proto.RegisterType((*ReadLinkResponse)(nil), "grpc.ReadLinkResponse")
	proto.RegisterType((*UpdateLinkRequest)(nil), "grpc.UpdateLinkRequest")
	proto.RegisterType((*UpdateLinkResponse)(nil), "grpc.UpdateLinkResponse")
	proto.RegisterType((*DeleteLinkRequest)(nil), "grpc.DeleteLinkRequest")
	proto.RegisterType((*DeleteLinkResponse)(nil), "grpc.DeleteLinkResponse")
	proto.RegisterType((*CreateAliasRequest)(nil), "grpc.CreateAliasRequest")
	proto.RegisterType((*CreateAliasResponse)(nil), "grpc.CreateAliasResponse")
	proto.RegisterType((*ReadAliasRequest)(nil), "grpc.ReadAliasRequest")
	proto.RegisterType((*ReadAliasResponse)(nil), "grpc.ReadAliasResponse")
	proto.RegisterType((*UpdateAliasRequest)(nil), "grpc.UpdateAliasRequest")
	proto.RegisterType((*UpdateAliasResponse)(nil), "grpc.UpdateAliasResponse")
	proto.RegisterType((*DeleteAliasRequest)(nil), "grpc.DeleteAliasRequest")
	proto.RegisterType((*DeleteAliasResponse)(nil), "grpc.DeleteAliasResponse")
	proto.RegisterType((*CreateTargetRequest)(nil), "grpc.CreateTargetRequest")
	proto.RegisterType((*CreateTargetResponse)(nil), "grpc.CreateTargetResponse")
	proto.RegisterType((*ReadTargetRequest)(nil), "grpc.ReadTargetRequest")
	proto.RegisterType((*ReadTargetResponse)(nil), "grpc.ReadTargetResponse")
	proto.RegisterType((*UpdateTargetRequest)(nil), "grpc.UpdateTargetRequest")
	proto.RegisterType((*UpdateTargetResponse)(nil), "grpc.UpdateTargetResponse")
	proto.RegisterType((*DeleteTargetRequest)(nil), "grpc.DeleteTargetRequest")
	proto.RegisterType((*DeleteTargetResponse)(nil), "grpc.DeleteTargetResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NamespaceClient is the client API for Namespace service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NamespaceClient interface {
	Create(ctx context.Context, in *CreateNamespaceRequest, opts ...grpc.CallOption) (*CreateNamespaceResponse, error)
	Read(ctx context.Context, in *ReadNamespaceRequest, opts ...grpc.CallOption) (*ReadNamespaceResponse, error)
	Update(ctx context.Context, in *UpdateNamespaceRequest, opts ...grpc.CallOption) (*UpdateNamespaceResponse, error)
	Delete(ctx context.Context, in *DeleteNamespaceRequest, opts ...grpc.CallOption) (*DeleteNamespaceResponse, error)
}

type namespaceClient struct {
	cc *grpc.ClientConn
}

func NewNamespaceClient(cc *grpc.ClientConn) NamespaceClient {
	return &namespaceClient{cc}
}

func (c *namespaceClient) Create(ctx context.Context, in *CreateNamespaceRequest, opts ...grpc.CallOption) (*CreateNamespaceResponse, error) {
	out := new(CreateNamespaceResponse)
	err := c.cc.Invoke(ctx, "/grpc.Namespace/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *namespaceClient) Read(ctx context.Context, in *ReadNamespaceRequest, opts ...grpc.CallOption) (*ReadNamespaceResponse, error) {
	out := new(ReadNamespaceResponse)
	err := c.cc.Invoke(ctx, "/grpc.Namespace/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *namespaceClient) Update(ctx context.Context, in *UpdateNamespaceRequest, opts ...grpc.CallOption) (*UpdateNamespaceResponse, error) {
	out := new(UpdateNamespaceResponse)
	err := c.cc.Invoke(ctx, "/grpc.Namespace/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *namespaceClient) Delete(ctx context.Context, in *DeleteNamespaceRequest, opts ...grpc.CallOption) (*DeleteNamespaceResponse, error) {
	out := new(DeleteNamespaceResponse)
	err := c.cc.Invoke(ctx, "/grpc.Namespace/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NamespaceServer is the server API for Namespace service.
type NamespaceServer interface {
	Create(context.Context, *CreateNamespaceRequest) (*CreateNamespaceResponse, error)
	Read(context.Context, *ReadNamespaceRequest) (*ReadNamespaceResponse, error)
	Update(context.Context, *UpdateNamespaceRequest) (*UpdateNamespaceResponse, error)
	Delete(context.Context, *DeleteNamespaceRequest) (*DeleteNamespaceResponse, error)
}

func RegisterNamespaceServer(s *grpc.Server, srv NamespaceServer) {
	s.RegisterService(&_Namespace_serviceDesc, srv)
}

func _Namespace_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNamespaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NamespaceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Namespace/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NamespaceServer).Create(ctx, req.(*CreateNamespaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Namespace_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadNamespaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NamespaceServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Namespace/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NamespaceServer).Read(ctx, req.(*ReadNamespaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Namespace_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateNamespaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NamespaceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Namespace/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NamespaceServer).Update(ctx, req.(*UpdateNamespaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Namespace_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteNamespaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NamespaceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Namespace/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NamespaceServer).Delete(ctx, req.(*DeleteNamespaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Namespace_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.Namespace",
	HandlerType: (*NamespaceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Namespace_Create_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _Namespace_Read_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Namespace_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Namespace_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "storage.proto",
}

// LinkClient is the client API for Link service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LinkClient interface {
	Create(ctx context.Context, in *CreateLinkRequest, opts ...grpc.CallOption) (*CreateLinkResponse, error)
	Read(ctx context.Context, in *ReadLinkRequest, opts ...grpc.CallOption) (*ReadLinkResponse, error)
	Update(ctx context.Context, in *UpdateLinkRequest, opts ...grpc.CallOption) (*UpdateLinkResponse, error)
	Delete(ctx context.Context, in *DeleteLinkRequest, opts ...grpc.CallOption) (*DeleteLinkResponse, error)
}

type linkClient struct {
	cc *grpc.ClientConn
}

func NewLinkClient(cc *grpc.ClientConn) LinkClient {
	return &linkClient{cc}
}

func (c *linkClient) Create(ctx context.Context, in *CreateLinkRequest, opts ...grpc.CallOption) (*CreateLinkResponse, error) {
	out := new(CreateLinkResponse)
	err := c.cc.Invoke(ctx, "/grpc.Link/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linkClient) Read(ctx context.Context, in *ReadLinkRequest, opts ...grpc.CallOption) (*ReadLinkResponse, error) {
	out := new(ReadLinkResponse)
	err := c.cc.Invoke(ctx, "/grpc.Link/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linkClient) Update(ctx context.Context, in *UpdateLinkRequest, opts ...grpc.CallOption) (*UpdateLinkResponse, error) {
	out := new(UpdateLinkResponse)
	err := c.cc.Invoke(ctx, "/grpc.Link/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linkClient) Delete(ctx context.Context, in *DeleteLinkRequest, opts ...grpc.CallOption) (*DeleteLinkResponse, error) {
	out := new(DeleteLinkResponse)
	err := c.cc.Invoke(ctx, "/grpc.Link/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LinkServer is the server API for Link service.
type LinkServer interface {
	Create(context.Context, *CreateLinkRequest) (*CreateLinkResponse, error)
	Read(context.Context, *ReadLinkRequest) (*ReadLinkResponse, error)
	Update(context.Context, *UpdateLinkRequest) (*UpdateLinkResponse, error)
	Delete(context.Context, *DeleteLinkRequest) (*DeleteLinkResponse, error)
}

func RegisterLinkServer(s *grpc.Server, srv LinkServer) {
	s.RegisterService(&_Link_serviceDesc, srv)
}

func _Link_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinkServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Link/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinkServer).Create(ctx, req.(*CreateLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Link_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinkServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Link/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinkServer).Read(ctx, req.(*ReadLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Link_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinkServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Link/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinkServer).Update(ctx, req.(*UpdateLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Link_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinkServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Link/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinkServer).Delete(ctx, req.(*DeleteLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Link_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.Link",
	HandlerType: (*LinkServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Link_Create_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _Link_Read_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Link_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Link_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "storage.proto",
}

// AliasClient is the client API for Alias service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AliasClient interface {
	Create(ctx context.Context, in *CreateAliasRequest, opts ...grpc.CallOption) (*CreateAliasResponse, error)
	Read(ctx context.Context, in *ReadAliasRequest, opts ...grpc.CallOption) (*ReadAliasResponse, error)
	Update(ctx context.Context, in *UpdateAliasRequest, opts ...grpc.CallOption) (*UpdateAliasResponse, error)
	Delete(ctx context.Context, in *DeleteAliasRequest, opts ...grpc.CallOption) (*DeleteAliasResponse, error)
}

type aliasClient struct {
	cc *grpc.ClientConn
}

func NewAliasClient(cc *grpc.ClientConn) AliasClient {
	return &aliasClient{cc}
}

func (c *aliasClient) Create(ctx context.Context, in *CreateAliasRequest, opts ...grpc.CallOption) (*CreateAliasResponse, error) {
	out := new(CreateAliasResponse)
	err := c.cc.Invoke(ctx, "/grpc.Alias/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aliasClient) Read(ctx context.Context, in *ReadAliasRequest, opts ...grpc.CallOption) (*ReadAliasResponse, error) {
	out := new(ReadAliasResponse)
	err := c.cc.Invoke(ctx, "/grpc.Alias/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aliasClient) Update(ctx context.Context, in *UpdateAliasRequest, opts ...grpc.CallOption) (*UpdateAliasResponse, error) {
	out := new(UpdateAliasResponse)
	err := c.cc.Invoke(ctx, "/grpc.Alias/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aliasClient) Delete(ctx context.Context, in *DeleteAliasRequest, opts ...grpc.CallOption) (*DeleteAliasResponse, error) {
	out := new(DeleteAliasResponse)
	err := c.cc.Invoke(ctx, "/grpc.Alias/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AliasServer is the server API for Alias service.
type AliasServer interface {
	Create(context.Context, *CreateAliasRequest) (*CreateAliasResponse, error)
	Read(context.Context, *ReadAliasRequest) (*ReadAliasResponse, error)
	Update(context.Context, *UpdateAliasRequest) (*UpdateAliasResponse, error)
	Delete(context.Context, *DeleteAliasRequest) (*DeleteAliasResponse, error)
}

func RegisterAliasServer(s *grpc.Server, srv AliasServer) {
	s.RegisterService(&_Alias_serviceDesc, srv)
}

func _Alias_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAliasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AliasServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Alias/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AliasServer).Create(ctx, req.(*CreateAliasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Alias_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadAliasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AliasServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Alias/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AliasServer).Read(ctx, req.(*ReadAliasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Alias_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAliasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AliasServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Alias/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AliasServer).Update(ctx, req.(*UpdateAliasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Alias_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAliasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AliasServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Alias/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AliasServer).Delete(ctx, req.(*DeleteAliasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Alias_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.Alias",
	HandlerType: (*AliasServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Alias_Create_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _Alias_Read_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Alias_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Alias_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "storage.proto",
}

// TargetClient is the client API for Target service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TargetClient interface {
	Create(ctx context.Context, in *CreateTargetRequest, opts ...grpc.CallOption) (*CreateTargetResponse, error)
	Read(ctx context.Context, in *ReadTargetRequest, opts ...grpc.CallOption) (*ReadTargetResponse, error)
	Update(ctx context.Context, in *UpdateTargetRequest, opts ...grpc.CallOption) (*UpdateTargetResponse, error)
	Delete(ctx context.Context, in *DeleteTargetRequest, opts ...grpc.CallOption) (*DeleteTargetResponse, error)
}

type targetClient struct {
	cc *grpc.ClientConn
}

func NewTargetClient(cc *grpc.ClientConn) TargetClient {
	return &targetClient{cc}
}

func (c *targetClient) Create(ctx context.Context, in *CreateTargetRequest, opts ...grpc.CallOption) (*CreateTargetResponse, error) {
	out := new(CreateTargetResponse)
	err := c.cc.Invoke(ctx, "/grpc.Target/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetClient) Read(ctx context.Context, in *ReadTargetRequest, opts ...grpc.CallOption) (*ReadTargetResponse, error) {
	out := new(ReadTargetResponse)
	err := c.cc.Invoke(ctx, "/grpc.Target/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetClient) Update(ctx context.Context, in *UpdateTargetRequest, opts ...grpc.CallOption) (*UpdateTargetResponse, error) {
	out := new(UpdateTargetResponse)
	err := c.cc.Invoke(ctx, "/grpc.Target/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetClient) Delete(ctx context.Context, in *DeleteTargetRequest, opts ...grpc.CallOption) (*DeleteTargetResponse, error) {
	out := new(DeleteTargetResponse)
	err := c.cc.Invoke(ctx, "/grpc.Target/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TargetServer is the server API for Target service.
type TargetServer interface {
	Create(context.Context, *CreateTargetRequest) (*CreateTargetResponse, error)
	Read(context.Context, *ReadTargetRequest) (*ReadTargetResponse, error)
	Update(context.Context, *UpdateTargetRequest) (*UpdateTargetResponse, error)
	Delete(context.Context, *DeleteTargetRequest) (*DeleteTargetResponse, error)
}

func RegisterTargetServer(s *grpc.Server, srv TargetServer) {
	s.RegisterService(&_Target_serviceDesc, srv)
}

func _Target_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTargetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Target/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetServer).Create(ctx, req.(*CreateTargetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Target_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadTargetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Target/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetServer).Read(ctx, req.(*ReadTargetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Target_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTargetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Target/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetServer).Update(ctx, req.(*UpdateTargetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Target_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTargetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Target/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetServer).Delete(ctx, req.(*DeleteTargetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Target_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.Target",
	HandlerType: (*TargetServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Target_Create_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _Target_Read_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Target_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Target_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "storage.proto",
}

func init() { proto.RegisterFile("storage.proto", fileDescriptor_storage_66e1adc07c3c018b) }

var fileDescriptor_storage_66e1adc07c3c018b = []byte{
	// 491 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x55, 0x4b, 0x6a, 0xe3, 0x50,
	0x10, 0xd4, 0x18, 0x8f, 0x60, 0x1a, 0x86, 0x19, 0x3f, 0xcb, 0x92, 0xac, 0x99, 0xd9, 0xe8, 0x00,
	0x5e, 0x68, 0x16, 0x21, 0x04, 0x63, 0x4c, 0x02, 0xde, 0x84, 0x2c, 0x4c, 0x72, 0x00, 0xc5, 0x7e,
	0x18, 0x13, 0xc7, 0x52, 0x24, 0xe5, 0x08, 0xd9, 0xe6, 0x1e, 0xb9, 0x63, 0x16, 0x41, 0x7a, 0xdf,
	0xd6, 0x6b, 0x6d, 0xab, 0xab, 0x4b, 0x55, 0xc5, 0x6b, 0x1b, 0x7e, 0xd6, 0x4d, 0x51, 0xe5, 0x07,
	0xbe, 0x28, 0xab, 0xa2, 0x29, 0xd8, 0xf8, 0x50, 0x95, 0xbb, 0x34, 0x86, 0xf0, 0xba, 0xe2, 0x79,
	0xc3, 0xef, 0xf2, 0x67, 0x5e, 0x97, 0xf9, 0x8e, 0x6f, 0xf9, 0xcb, 0x2b, 0xaf, 0x9b, 0x74, 0x0e,
	0x91, 0x33, 0xa9, 0xcb, 0xe2, 0x5c, 0xf3, 0x34, 0x84, 0x60, 0xcb, 0xf3, 0xbd, 0xb3, 0x12, 0xc1,
	0xac, 0x87, 0xcb, 0x85, 0x18, 0xc2, 0x87, 0x72, 0x3f, 0xf0, 0x15, 0x67, 0x62, 0x96, 0x6e, 0xf8,
	0x89, 0xd3, 0x4b, 0xce, 0x44, 0x2e, 0x4d, 0x61, 0x22, 0x5c, 0xdf, 0x1e, 0xcf, 0x4f, 0x8a, 0x1f,
	0x00, 0xb3, 0x41, 0x49, 0x9d, 0xc0, 0xaf, 0xd6, 0xad, 0x4d, 0x64, 0xf0, 0xdb, 0x40, 0x46, 0x51,
	0x38, 0xec, 0x29, 0xda, 0xa0, 0xa1, 0x0a, 0x5f, 0x3d, 0xaa, 0x0d, 0x4a, 0xaa, 0xb6, 0xb4, 0x3e,
	0x1d, 0xf3, 0x5a, 0x71, 0x67, 0x30, 0x45, 0xa8, 0x24, 0x4b, 0x5b, 0x88, 0x3a, 0x85, 0x89, 0x85,
	0x19, 0x55, 0x61, 0xab, 0xaf, 0x8a, 0x50, 0x43, 0x16, 0xc6, 0xfa, 0x64, 0x84, 0x4a, 0xb2, 0x76,
	0x76, 0x9f, 0x57, 0x07, 0xde, 0x28, 0x76, 0x08, 0x01, 0x86, 0x4d, 0x13, 0xad, 0x3b, 0x4c, 0x0e,
	0x80, 0xd9, 0xa0, 0x51, 0x16, 0xee, 0x1c, 0x65, 0x0c, 0x1b, 0xba, 0xf0, 0xe7, 0xd0, 0x31, 0x2c,
	0xe8, 0xd9, 0xc7, 0x08, 0x7e, 0xe8, 0x57, 0xc2, 0x36, 0xe0, 0x0b, 0xbb, 0xec, 0xef, 0xa2, 0x7d,
	0xfe, 0x0b, 0xfa, 0xed, 0x27, 0xff, 0x06, 0xa6, 0xd2, 0x83, 0xc7, 0xd6, 0x30, 0x6e, 0xa3, 0xb0,
	0x44, 0x10, 0xa9, 0x6b, 0x48, 0xfe, 0x90, 0x33, 0x2d, 0xb1, 0x01, 0x5f, 0x04, 0x54, 0x5e, 0xe8,
	0x0b, 0x51, 0x5e, 0x86, 0xae, 0xa4, 0x13, 0x12, 0xd1, 0x95, 0x10, 0x7d, 0x35, 0x4a, 0x68, 0xe8,
	0x72, 0xbc, 0xec, 0xf3, 0x1b, 0x8c, 0xdb, 0x47, 0xca, 0x96, 0xba, 0xa6, 0xc8, 0x2e, 0xc2, 0x7a,
	0xd5, 0x49, 0xec, 0x0e, 0xb4, 0xa1, 0x0b, 0x59, 0xce, 0xcc, 0x14, 0x60, 0xaf, 0x86, 0x7d, 0x58,
	0x2f, 0x2e, 0x75, 0x25, 0x91, 0x1d, 0x9a, 0xf8, 0x2e, 0x71, 0x7c, 0xdd, 0xba, 0x2c, 0x22, 0xb2,
	0xa3, 0x12, 0xeb, 0xc4, 0x41, 0x7a, 0xd9, 0xdb, 0x08, 0xbe, 0x77, 0x8f, 0x9e, 0xad, 0x74, 0x7e,
	0x14, 0xd3, 0xbe, 0x93, 0x64, 0x4e, 0x4c, 0xb4, 0x93, 0x4b, 0xd9, 0x80, 0x15, 0x15, 0x2d, 0x47,
	0x0e, 0xae, 0x57, 0x57, 0xba, 0x03, 0x14, 0x95, 0xfa, 0x36, 0x75, 0xd4, 0x9d, 0x80, 0x6c, 0x01,
	0x85, 0xa5, 0x04, 0xa8, 0x43, 0xf7, 0xb2, 0xf7, 0x11, 0xf8, 0xe2, 0x8a, 0xd8, 0x5a, 0x17, 0x81,
	0xe2, 0xa2, 0xd3, 0x4b, 0x12, 0x6a, 0xa4, 0xed, 0x5c, 0xc9, 0x2a, 0xac, 0xc8, 0x78, 0x3d, 0x76,
	0x07, 0xd6, 0x99, 0xa9, 0x32, 0x50, 0x64, 0xf2, 0xfb, 0xe4, 0xaf, 0x45, 0x27, 0x21, 0xeb, 0x40,
	0xa1, 0x49, 0x09, 0xea, 0x17, 0x24, 0xf5, 0x1e, 0xfd, 0xee, 0x0f, 0xf3, 0xff, 0x57, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xb8, 0x7b, 0xe7, 0xd0, 0x41, 0x07, 0x00, 0x00,
}
