// Code generated by protoc-gen-go. DO NOT EDIT.
// source: event.proto

package grpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ReadLogRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadLogRequest) Reset()         { *m = ReadLogRequest{} }
func (m *ReadLogRequest) String() string { return proto.CompactTextString(m) }
func (*ReadLogRequest) ProtoMessage()    {}
func (*ReadLogRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_event_47cc2ad71607aafd, []int{0}
}
func (m *ReadLogRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadLogRequest.Unmarshal(m, b)
}
func (m *ReadLogRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadLogRequest.Marshal(b, m, deterministic)
}
func (dst *ReadLogRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadLogRequest.Merge(dst, src)
}
func (m *ReadLogRequest) XXX_Size() int {
	return xxx_messageInfo_ReadLogRequest.Size(m)
}
func (m *ReadLogRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadLogRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadLogRequest proto.InternalMessageInfo

type ReadLogResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadLogResponse) Reset()         { *m = ReadLogResponse{} }
func (m *ReadLogResponse) String() string { return proto.CompactTextString(m) }
func (*ReadLogResponse) ProtoMessage()    {}
func (*ReadLogResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_event_47cc2ad71607aafd, []int{1}
}
func (m *ReadLogResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadLogResponse.Unmarshal(m, b)
}
func (m *ReadLogResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadLogResponse.Marshal(b, m, deterministic)
}
func (dst *ReadLogResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadLogResponse.Merge(dst, src)
}
func (m *ReadLogResponse) XXX_Size() int {
	return xxx_messageInfo_ReadLogResponse.Size(m)
}
func (m *ReadLogResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadLogResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadLogResponse proto.InternalMessageInfo

type ListenLogRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListenLogRequest) Reset()         { *m = ListenLogRequest{} }
func (m *ListenLogRequest) String() string { return proto.CompactTextString(m) }
func (*ListenLogRequest) ProtoMessage()    {}
func (*ListenLogRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_event_47cc2ad71607aafd, []int{2}
}
func (m *ListenLogRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListenLogRequest.Unmarshal(m, b)
}
func (m *ListenLogRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListenLogRequest.Marshal(b, m, deterministic)
}
func (dst *ListenLogRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListenLogRequest.Merge(dst, src)
}
func (m *ListenLogRequest) XXX_Size() int {
	return xxx_messageInfo_ListenLogRequest.Size(m)
}
func (m *ListenLogRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListenLogRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListenLogRequest proto.InternalMessageInfo

type ListenLogResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListenLogResponse) Reset()         { *m = ListenLogResponse{} }
func (m *ListenLogResponse) String() string { return proto.CompactTextString(m) }
func (*ListenLogResponse) ProtoMessage()    {}
func (*ListenLogResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_event_47cc2ad71607aafd, []int{3}
}
func (m *ListenLogResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListenLogResponse.Unmarshal(m, b)
}
func (m *ListenLogResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListenLogResponse.Marshal(b, m, deterministic)
}
func (dst *ListenLogResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListenLogResponse.Merge(dst, src)
}
func (m *ListenLogResponse) XXX_Size() int {
	return xxx_messageInfo_ListenLogResponse.Size(m)
}
func (m *ListenLogResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListenLogResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListenLogResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ReadLogRequest)(nil), "grpc.ReadLogRequest")
	proto.RegisterType((*ReadLogResponse)(nil), "grpc.ReadLogResponse")
	proto.RegisterType((*ListenLogRequest)(nil), "grpc.ListenLogRequest")
	proto.RegisterType((*ListenLogResponse)(nil), "grpc.ListenLogResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LogClient is the client API for Log service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LogClient interface {
	Read(ctx context.Context, in *ReadLogRequest, opts ...grpc.CallOption) (*ReadLogRequest, error)
	Listen(ctx context.Context, in *ListenLogRequest, opts ...grpc.CallOption) (Log_ListenClient, error)
}

type logClient struct {
	cc *grpc.ClientConn
}

func NewLogClient(cc *grpc.ClientConn) LogClient {
	return &logClient{cc}
}

func (c *logClient) Read(ctx context.Context, in *ReadLogRequest, opts ...grpc.CallOption) (*ReadLogRequest, error) {
	out := new(ReadLogRequest)
	err := c.cc.Invoke(ctx, "/grpc.Log/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logClient) Listen(ctx context.Context, in *ListenLogRequest, opts ...grpc.CallOption) (Log_ListenClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Log_serviceDesc.Streams[0], "/grpc.Log/Listen", opts...)
	if err != nil {
		return nil, err
	}
	x := &logListenClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Log_ListenClient interface {
	Recv() (*ListenLogResponse, error)
	grpc.ClientStream
}

type logListenClient struct {
	grpc.ClientStream
}

func (x *logListenClient) Recv() (*ListenLogResponse, error) {
	m := new(ListenLogResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// LogServer is the server API for Log service.
type LogServer interface {
	Read(context.Context, *ReadLogRequest) (*ReadLogRequest, error)
	Listen(*ListenLogRequest, Log_ListenServer) error
}

func RegisterLogServer(s *grpc.Server, srv LogServer) {
	s.RegisterService(&_Log_serviceDesc, srv)
}

func _Log_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Log/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogServer).Read(ctx, req.(*ReadLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Log_Listen_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListenLogRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LogServer).Listen(m, &logListenServer{stream})
}

type Log_ListenServer interface {
	Send(*ListenLogResponse) error
	grpc.ServerStream
}

type logListenServer struct {
	grpc.ServerStream
}

func (x *logListenServer) Send(m *ListenLogResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _Log_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.Log",
	HandlerType: (*LogServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Read",
			Handler:    _Log_Read_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Listen",
			Handler:       _Log_Listen_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "event.proto",
}

func init() { proto.RegisterFile("event.proto", fileDescriptor_event_47cc2ad71607aafd) }

var fileDescriptor_event_47cc2ad71607aafd = []byte{
	// 146 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0x2d, 0x4b, 0xcd,
	0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x49, 0x2f, 0x2a, 0x48, 0x56, 0x12, 0xe0,
	0xe2, 0x0b, 0x4a, 0x4d, 0x4c, 0xf1, 0xc9, 0x4f, 0x0f, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x51,
	0x12, 0xe4, 0xe2, 0x87, 0x8b, 0x14, 0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x2a, 0x09, 0x71, 0x09, 0xf8,
	0x64, 0x16, 0x97, 0xa4, 0xe6, 0x21, 0x29, 0x13, 0xe6, 0x12, 0x44, 0x12, 0x83, 0x28, 0x34, 0xaa,
	0xe2, 0x62, 0xf6, 0xc9, 0x4f, 0x17, 0x32, 0xe1, 0x62, 0x01, 0x19, 0x21, 0x24, 0xa2, 0x07, 0xb2,
	0x43, 0x0f, 0xd5, 0x02, 0x29, 0xac, 0xa2, 0x4a, 0x0c, 0x42, 0xb6, 0x5c, 0x6c, 0x10, 0x13, 0x85,
	0xc4, 0x20, 0x2a, 0xd0, 0xed, 0x94, 0x12, 0xc7, 0x10, 0x87, 0x3a, 0x90, 0xc1, 0x80, 0x31, 0x89,
	0x0d, 0xec, 0x2d, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xfe, 0x9d, 0xc0, 0xe6, 0xe5, 0x00,
	0x00, 0x00,
}
