// Code generated by protoc-gen-go. DO NOT EDIT.
// source: storage.proto

package storage

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateLinkRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateLinkRequest) Reset()         { *m = CreateLinkRequest{} }
func (m *CreateLinkRequest) String() string { return proto.CompactTextString(m) }
func (*CreateLinkRequest) ProtoMessage()    {}
func (*CreateLinkRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_c8c8f9ebcb464848, []int{0}
}
func (m *CreateLinkRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateLinkRequest.Unmarshal(m, b)
}
func (m *CreateLinkRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateLinkRequest.Marshal(b, m, deterministic)
}
func (dst *CreateLinkRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateLinkRequest.Merge(dst, src)
}
func (m *CreateLinkRequest) XXX_Size() int {
	return xxx_messageInfo_CreateLinkRequest.Size(m)
}
func (m *CreateLinkRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateLinkRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateLinkRequest proto.InternalMessageInfo

type CreateLinkResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateLinkResponse) Reset()         { *m = CreateLinkResponse{} }
func (m *CreateLinkResponse) String() string { return proto.CompactTextString(m) }
func (*CreateLinkResponse) ProtoMessage()    {}
func (*CreateLinkResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_c8c8f9ebcb464848, []int{1}
}
func (m *CreateLinkResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateLinkResponse.Unmarshal(m, b)
}
func (m *CreateLinkResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateLinkResponse.Marshal(b, m, deterministic)
}
func (dst *CreateLinkResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateLinkResponse.Merge(dst, src)
}
func (m *CreateLinkResponse) XXX_Size() int {
	return xxx_messageInfo_CreateLinkResponse.Size(m)
}
func (m *CreateLinkResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateLinkResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateLinkResponse proto.InternalMessageInfo

type ReadLinkRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadLinkRequest) Reset()         { *m = ReadLinkRequest{} }
func (m *ReadLinkRequest) String() string { return proto.CompactTextString(m) }
func (*ReadLinkRequest) ProtoMessage()    {}
func (*ReadLinkRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_c8c8f9ebcb464848, []int{2}
}
func (m *ReadLinkRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadLinkRequest.Unmarshal(m, b)
}
func (m *ReadLinkRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadLinkRequest.Marshal(b, m, deterministic)
}
func (dst *ReadLinkRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadLinkRequest.Merge(dst, src)
}
func (m *ReadLinkRequest) XXX_Size() int {
	return xxx_messageInfo_ReadLinkRequest.Size(m)
}
func (m *ReadLinkRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadLinkRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadLinkRequest proto.InternalMessageInfo

type ReadLinkResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadLinkResponse) Reset()         { *m = ReadLinkResponse{} }
func (m *ReadLinkResponse) String() string { return proto.CompactTextString(m) }
func (*ReadLinkResponse) ProtoMessage()    {}
func (*ReadLinkResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_c8c8f9ebcb464848, []int{3}
}
func (m *ReadLinkResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadLinkResponse.Unmarshal(m, b)
}
func (m *ReadLinkResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadLinkResponse.Marshal(b, m, deterministic)
}
func (dst *ReadLinkResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadLinkResponse.Merge(dst, src)
}
func (m *ReadLinkResponse) XXX_Size() int {
	return xxx_messageInfo_ReadLinkResponse.Size(m)
}
func (m *ReadLinkResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadLinkResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadLinkResponse proto.InternalMessageInfo

type UpdateLinkRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateLinkRequest) Reset()         { *m = UpdateLinkRequest{} }
func (m *UpdateLinkRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateLinkRequest) ProtoMessage()    {}
func (*UpdateLinkRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_c8c8f9ebcb464848, []int{4}
}
func (m *UpdateLinkRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateLinkRequest.Unmarshal(m, b)
}
func (m *UpdateLinkRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateLinkRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateLinkRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateLinkRequest.Merge(dst, src)
}
func (m *UpdateLinkRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateLinkRequest.Size(m)
}
func (m *UpdateLinkRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateLinkRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateLinkRequest proto.InternalMessageInfo

type UpdateLinkResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateLinkResponse) Reset()         { *m = UpdateLinkResponse{} }
func (m *UpdateLinkResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateLinkResponse) ProtoMessage()    {}
func (*UpdateLinkResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_c8c8f9ebcb464848, []int{5}
}
func (m *UpdateLinkResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateLinkResponse.Unmarshal(m, b)
}
func (m *UpdateLinkResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateLinkResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateLinkResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateLinkResponse.Merge(dst, src)
}
func (m *UpdateLinkResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateLinkResponse.Size(m)
}
func (m *UpdateLinkResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateLinkResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateLinkResponse proto.InternalMessageInfo

type DeleteLinkRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteLinkRequest) Reset()         { *m = DeleteLinkRequest{} }
func (m *DeleteLinkRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteLinkRequest) ProtoMessage()    {}
func (*DeleteLinkRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_c8c8f9ebcb464848, []int{6}
}
func (m *DeleteLinkRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteLinkRequest.Unmarshal(m, b)
}
func (m *DeleteLinkRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteLinkRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteLinkRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteLinkRequest.Merge(dst, src)
}
func (m *DeleteLinkRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteLinkRequest.Size(m)
}
func (m *DeleteLinkRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteLinkRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteLinkRequest proto.InternalMessageInfo

type DeleteLinkResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteLinkResponse) Reset()         { *m = DeleteLinkResponse{} }
func (m *DeleteLinkResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteLinkResponse) ProtoMessage()    {}
func (*DeleteLinkResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_c8c8f9ebcb464848, []int{7}
}
func (m *DeleteLinkResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteLinkResponse.Unmarshal(m, b)
}
func (m *DeleteLinkResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteLinkResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteLinkResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteLinkResponse.Merge(dst, src)
}
func (m *DeleteLinkResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteLinkResponse.Size(m)
}
func (m *DeleteLinkResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteLinkResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteLinkResponse proto.InternalMessageInfo

type CreateAliasRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAliasRequest) Reset()         { *m = CreateAliasRequest{} }
func (m *CreateAliasRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAliasRequest) ProtoMessage()    {}
func (*CreateAliasRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_c8c8f9ebcb464848, []int{8}
}
func (m *CreateAliasRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAliasRequest.Unmarshal(m, b)
}
func (m *CreateAliasRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAliasRequest.Marshal(b, m, deterministic)
}
func (dst *CreateAliasRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAliasRequest.Merge(dst, src)
}
func (m *CreateAliasRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAliasRequest.Size(m)
}
func (m *CreateAliasRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAliasRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAliasRequest proto.InternalMessageInfo

type CreateAliasResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAliasResponse) Reset()         { *m = CreateAliasResponse{} }
func (m *CreateAliasResponse) String() string { return proto.CompactTextString(m) }
func (*CreateAliasResponse) ProtoMessage()    {}
func (*CreateAliasResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_c8c8f9ebcb464848, []int{9}
}
func (m *CreateAliasResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAliasResponse.Unmarshal(m, b)
}
func (m *CreateAliasResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAliasResponse.Marshal(b, m, deterministic)
}
func (dst *CreateAliasResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAliasResponse.Merge(dst, src)
}
func (m *CreateAliasResponse) XXX_Size() int {
	return xxx_messageInfo_CreateAliasResponse.Size(m)
}
func (m *CreateAliasResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAliasResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAliasResponse proto.InternalMessageInfo

type UpdateAliasRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateAliasRequest) Reset()         { *m = UpdateAliasRequest{} }
func (m *UpdateAliasRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateAliasRequest) ProtoMessage()    {}
func (*UpdateAliasRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_c8c8f9ebcb464848, []int{10}
}
func (m *UpdateAliasRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAliasRequest.Unmarshal(m, b)
}
func (m *UpdateAliasRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAliasRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateAliasRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAliasRequest.Merge(dst, src)
}
func (m *UpdateAliasRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateAliasRequest.Size(m)
}
func (m *UpdateAliasRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAliasRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAliasRequest proto.InternalMessageInfo

type UpdateAliasResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateAliasResponse) Reset()         { *m = UpdateAliasResponse{} }
func (m *UpdateAliasResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateAliasResponse) ProtoMessage()    {}
func (*UpdateAliasResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_c8c8f9ebcb464848, []int{11}
}
func (m *UpdateAliasResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAliasResponse.Unmarshal(m, b)
}
func (m *UpdateAliasResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAliasResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateAliasResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAliasResponse.Merge(dst, src)
}
func (m *UpdateAliasResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateAliasResponse.Size(m)
}
func (m *UpdateAliasResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAliasResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAliasResponse proto.InternalMessageInfo

type DeleteAliasRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAliasRequest) Reset()         { *m = DeleteAliasRequest{} }
func (m *DeleteAliasRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteAliasRequest) ProtoMessage()    {}
func (*DeleteAliasRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_c8c8f9ebcb464848, []int{12}
}
func (m *DeleteAliasRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAliasRequest.Unmarshal(m, b)
}
func (m *DeleteAliasRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAliasRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteAliasRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAliasRequest.Merge(dst, src)
}
func (m *DeleteAliasRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteAliasRequest.Size(m)
}
func (m *DeleteAliasRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAliasRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAliasRequest proto.InternalMessageInfo

type DeleteAliasResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAliasResponse) Reset()         { *m = DeleteAliasResponse{} }
func (m *DeleteAliasResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteAliasResponse) ProtoMessage()    {}
func (*DeleteAliasResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_c8c8f9ebcb464848, []int{13}
}
func (m *DeleteAliasResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAliasResponse.Unmarshal(m, b)
}
func (m *DeleteAliasResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAliasResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteAliasResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAliasResponse.Merge(dst, src)
}
func (m *DeleteAliasResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteAliasResponse.Size(m)
}
func (m *DeleteAliasResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAliasResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAliasResponse proto.InternalMessageInfo

type CreateTargetRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTargetRequest) Reset()         { *m = CreateTargetRequest{} }
func (m *CreateTargetRequest) String() string { return proto.CompactTextString(m) }
func (*CreateTargetRequest) ProtoMessage()    {}
func (*CreateTargetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_c8c8f9ebcb464848, []int{14}
}
func (m *CreateTargetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTargetRequest.Unmarshal(m, b)
}
func (m *CreateTargetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTargetRequest.Marshal(b, m, deterministic)
}
func (dst *CreateTargetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTargetRequest.Merge(dst, src)
}
func (m *CreateTargetRequest) XXX_Size() int {
	return xxx_messageInfo_CreateTargetRequest.Size(m)
}
func (m *CreateTargetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTargetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTargetRequest proto.InternalMessageInfo

type CreateTargetResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTargetResponse) Reset()         { *m = CreateTargetResponse{} }
func (m *CreateTargetResponse) String() string { return proto.CompactTextString(m) }
func (*CreateTargetResponse) ProtoMessage()    {}
func (*CreateTargetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_c8c8f9ebcb464848, []int{15}
}
func (m *CreateTargetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTargetResponse.Unmarshal(m, b)
}
func (m *CreateTargetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTargetResponse.Marshal(b, m, deterministic)
}
func (dst *CreateTargetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTargetResponse.Merge(dst, src)
}
func (m *CreateTargetResponse) XXX_Size() int {
	return xxx_messageInfo_CreateTargetResponse.Size(m)
}
func (m *CreateTargetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTargetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTargetResponse proto.InternalMessageInfo

type UpdateTargetRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateTargetRequest) Reset()         { *m = UpdateTargetRequest{} }
func (m *UpdateTargetRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateTargetRequest) ProtoMessage()    {}
func (*UpdateTargetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_c8c8f9ebcb464848, []int{16}
}
func (m *UpdateTargetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTargetRequest.Unmarshal(m, b)
}
func (m *UpdateTargetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTargetRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateTargetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTargetRequest.Merge(dst, src)
}
func (m *UpdateTargetRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateTargetRequest.Size(m)
}
func (m *UpdateTargetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTargetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTargetRequest proto.InternalMessageInfo

type UpdateTargetResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateTargetResponse) Reset()         { *m = UpdateTargetResponse{} }
func (m *UpdateTargetResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateTargetResponse) ProtoMessage()    {}
func (*UpdateTargetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_c8c8f9ebcb464848, []int{17}
}
func (m *UpdateTargetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTargetResponse.Unmarshal(m, b)
}
func (m *UpdateTargetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTargetResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateTargetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTargetResponse.Merge(dst, src)
}
func (m *UpdateTargetResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateTargetResponse.Size(m)
}
func (m *UpdateTargetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTargetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTargetResponse proto.InternalMessageInfo

type DeleteTargetRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteTargetRequest) Reset()         { *m = DeleteTargetRequest{} }
func (m *DeleteTargetRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteTargetRequest) ProtoMessage()    {}
func (*DeleteTargetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_c8c8f9ebcb464848, []int{18}
}
func (m *DeleteTargetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteTargetRequest.Unmarshal(m, b)
}
func (m *DeleteTargetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteTargetRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteTargetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteTargetRequest.Merge(dst, src)
}
func (m *DeleteTargetRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteTargetRequest.Size(m)
}
func (m *DeleteTargetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteTargetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteTargetRequest proto.InternalMessageInfo

type DeleteTargetResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteTargetResponse) Reset()         { *m = DeleteTargetResponse{} }
func (m *DeleteTargetResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteTargetResponse) ProtoMessage()    {}
func (*DeleteTargetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_c8c8f9ebcb464848, []int{19}
}
func (m *DeleteTargetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteTargetResponse.Unmarshal(m, b)
}
func (m *DeleteTargetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteTargetResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteTargetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteTargetResponse.Merge(dst, src)
}
func (m *DeleteTargetResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteTargetResponse.Size(m)
}
func (m *DeleteTargetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteTargetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteTargetResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*CreateLinkRequest)(nil), "CreateLinkRequest")
	proto.RegisterType((*CreateLinkResponse)(nil), "CreateLinkResponse")
	proto.RegisterType((*ReadLinkRequest)(nil), "ReadLinkRequest")
	proto.RegisterType((*ReadLinkResponse)(nil), "ReadLinkResponse")
	proto.RegisterType((*UpdateLinkRequest)(nil), "UpdateLinkRequest")
	proto.RegisterType((*UpdateLinkResponse)(nil), "UpdateLinkResponse")
	proto.RegisterType((*DeleteLinkRequest)(nil), "DeleteLinkRequest")
	proto.RegisterType((*DeleteLinkResponse)(nil), "DeleteLinkResponse")
	proto.RegisterType((*CreateAliasRequest)(nil), "CreateAliasRequest")
	proto.RegisterType((*CreateAliasResponse)(nil), "CreateAliasResponse")
	proto.RegisterType((*UpdateAliasRequest)(nil), "UpdateAliasRequest")
	proto.RegisterType((*UpdateAliasResponse)(nil), "UpdateAliasResponse")
	proto.RegisterType((*DeleteAliasRequest)(nil), "DeleteAliasRequest")
	proto.RegisterType((*DeleteAliasResponse)(nil), "DeleteAliasResponse")
	proto.RegisterType((*CreateTargetRequest)(nil), "CreateTargetRequest")
	proto.RegisterType((*CreateTargetResponse)(nil), "CreateTargetResponse")
	proto.RegisterType((*UpdateTargetRequest)(nil), "UpdateTargetRequest")
	proto.RegisterType((*UpdateTargetResponse)(nil), "UpdateTargetResponse")
	proto.RegisterType((*DeleteTargetRequest)(nil), "DeleteTargetRequest")
	proto.RegisterType((*DeleteTargetResponse)(nil), "DeleteTargetResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LinkClient is the client API for Link service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LinkClient interface {
	Create(ctx context.Context, in *CreateLinkRequest, opts ...grpc.CallOption) (*CreateLinkResponse, error)
	Read(ctx context.Context, in *ReadLinkRequest, opts ...grpc.CallOption) (*ReadLinkResponse, error)
	Update(ctx context.Context, in *UpdateLinkRequest, opts ...grpc.CallOption) (*UpdateLinkResponse, error)
	Delete(ctx context.Context, in *DeleteLinkRequest, opts ...grpc.CallOption) (*DeleteLinkResponse, error)
}

type linkClient struct {
	cc *grpc.ClientConn
}

func NewLinkClient(cc *grpc.ClientConn) LinkClient {
	return &linkClient{cc}
}

func (c *linkClient) Create(ctx context.Context, in *CreateLinkRequest, opts ...grpc.CallOption) (*CreateLinkResponse, error) {
	out := new(CreateLinkResponse)
	err := c.cc.Invoke(ctx, "/Link/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linkClient) Read(ctx context.Context, in *ReadLinkRequest, opts ...grpc.CallOption) (*ReadLinkResponse, error) {
	out := new(ReadLinkResponse)
	err := c.cc.Invoke(ctx, "/Link/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linkClient) Update(ctx context.Context, in *UpdateLinkRequest, opts ...grpc.CallOption) (*UpdateLinkResponse, error) {
	out := new(UpdateLinkResponse)
	err := c.cc.Invoke(ctx, "/Link/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linkClient) Delete(ctx context.Context, in *DeleteLinkRequest, opts ...grpc.CallOption) (*DeleteLinkResponse, error) {
	out := new(DeleteLinkResponse)
	err := c.cc.Invoke(ctx, "/Link/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LinkServer is the server API for Link service.
type LinkServer interface {
	Create(context.Context, *CreateLinkRequest) (*CreateLinkResponse, error)
	Read(context.Context, *ReadLinkRequest) (*ReadLinkResponse, error)
	Update(context.Context, *UpdateLinkRequest) (*UpdateLinkResponse, error)
	Delete(context.Context, *DeleteLinkRequest) (*DeleteLinkResponse, error)
}

func RegisterLinkServer(s *grpc.Server, srv LinkServer) {
	s.RegisterService(&_Link_serviceDesc, srv)
}

func _Link_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinkServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Link/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinkServer).Create(ctx, req.(*CreateLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Link_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinkServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Link/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinkServer).Read(ctx, req.(*ReadLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Link_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinkServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Link/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinkServer).Update(ctx, req.(*UpdateLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Link_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinkServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Link/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinkServer).Delete(ctx, req.(*DeleteLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Link_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Link",
	HandlerType: (*LinkServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Link_Create_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _Link_Read_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Link_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Link_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "storage.proto",
}

// AliasClient is the client API for Alias service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AliasClient interface {
	Create(ctx context.Context, in *CreateAliasRequest, opts ...grpc.CallOption) (*CreateAliasResponse, error)
	Update(ctx context.Context, in *UpdateAliasRequest, opts ...grpc.CallOption) (*UpdateAliasResponse, error)
	Delete(ctx context.Context, in *DeleteAliasRequest, opts ...grpc.CallOption) (*DeleteAliasResponse, error)
}

type aliasClient struct {
	cc *grpc.ClientConn
}

func NewAliasClient(cc *grpc.ClientConn) AliasClient {
	return &aliasClient{cc}
}

func (c *aliasClient) Create(ctx context.Context, in *CreateAliasRequest, opts ...grpc.CallOption) (*CreateAliasResponse, error) {
	out := new(CreateAliasResponse)
	err := c.cc.Invoke(ctx, "/Alias/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aliasClient) Update(ctx context.Context, in *UpdateAliasRequest, opts ...grpc.CallOption) (*UpdateAliasResponse, error) {
	out := new(UpdateAliasResponse)
	err := c.cc.Invoke(ctx, "/Alias/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aliasClient) Delete(ctx context.Context, in *DeleteAliasRequest, opts ...grpc.CallOption) (*DeleteAliasResponse, error) {
	out := new(DeleteAliasResponse)
	err := c.cc.Invoke(ctx, "/Alias/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AliasServer is the server API for Alias service.
type AliasServer interface {
	Create(context.Context, *CreateAliasRequest) (*CreateAliasResponse, error)
	Update(context.Context, *UpdateAliasRequest) (*UpdateAliasResponse, error)
	Delete(context.Context, *DeleteAliasRequest) (*DeleteAliasResponse, error)
}

func RegisterAliasServer(s *grpc.Server, srv AliasServer) {
	s.RegisterService(&_Alias_serviceDesc, srv)
}

func _Alias_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAliasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AliasServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Alias/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AliasServer).Create(ctx, req.(*CreateAliasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Alias_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAliasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AliasServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Alias/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AliasServer).Update(ctx, req.(*UpdateAliasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Alias_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAliasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AliasServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Alias/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AliasServer).Delete(ctx, req.(*DeleteAliasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Alias_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Alias",
	HandlerType: (*AliasServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Alias_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Alias_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Alias_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "storage.proto",
}

// TargetClient is the client API for Target service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TargetClient interface {
	Create(ctx context.Context, in *CreateTargetRequest, opts ...grpc.CallOption) (*CreateTargetResponse, error)
	Update(ctx context.Context, in *UpdateTargetRequest, opts ...grpc.CallOption) (*UpdateTargetResponse, error)
	Delete(ctx context.Context, in *DeleteTargetRequest, opts ...grpc.CallOption) (*DeleteTargetResponse, error)
}

type targetClient struct {
	cc *grpc.ClientConn
}

func NewTargetClient(cc *grpc.ClientConn) TargetClient {
	return &targetClient{cc}
}

func (c *targetClient) Create(ctx context.Context, in *CreateTargetRequest, opts ...grpc.CallOption) (*CreateTargetResponse, error) {
	out := new(CreateTargetResponse)
	err := c.cc.Invoke(ctx, "/Target/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetClient) Update(ctx context.Context, in *UpdateTargetRequest, opts ...grpc.CallOption) (*UpdateTargetResponse, error) {
	out := new(UpdateTargetResponse)
	err := c.cc.Invoke(ctx, "/Target/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetClient) Delete(ctx context.Context, in *DeleteTargetRequest, opts ...grpc.CallOption) (*DeleteTargetResponse, error) {
	out := new(DeleteTargetResponse)
	err := c.cc.Invoke(ctx, "/Target/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TargetServer is the server API for Target service.
type TargetServer interface {
	Create(context.Context, *CreateTargetRequest) (*CreateTargetResponse, error)
	Update(context.Context, *UpdateTargetRequest) (*UpdateTargetResponse, error)
	Delete(context.Context, *DeleteTargetRequest) (*DeleteTargetResponse, error)
}

func RegisterTargetServer(s *grpc.Server, srv TargetServer) {
	s.RegisterService(&_Target_serviceDesc, srv)
}

func _Target_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTargetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Target/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetServer).Create(ctx, req.(*CreateTargetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Target_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTargetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Target/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetServer).Update(ctx, req.(*UpdateTargetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Target_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTargetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Target/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetServer).Delete(ctx, req.(*DeleteTargetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Target_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Target",
	HandlerType: (*TargetServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Target_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Target_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Target_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "storage.proto",
}

func init() { proto.RegisterFile("storage.proto", fileDescriptor_storage_c8c8f9ebcb464848) }

var fileDescriptor_storage_c8c8f9ebcb464848 = []byte{
	// 329 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x93, 0xbf, 0x4e, 0xf3, 0x40,
	0x10, 0xc4, 0xcf, 0x52, 0x3e, 0x17, 0x2b, 0x7d, 0x22, 0xde, 0x73, 0x28, 0xae, 0x74, 0xcf, 0x16,
	0x8e, 0x10, 0x35, 0x82, 0x92, 0x2a, 0x82, 0x07, 0x30, 0xca, 0x2a, 0x8a, 0x88, 0x62, 0x63, 0x9b,
	0xb7, 0xa2, 0xe3, 0x55, 0x78, 0x20, 0x64, 0xdf, 0x9d, 0xcf, 0xf7, 0xa7, 0x1d, 0xfd, 0x26, 0x33,
	0xbe, 0xd9, 0xc0, 0xff, 0x61, 0x6c, 0xfb, 0xe6, 0xc4, 0xd4, 0xf5, 0xed, 0xd8, 0x56, 0x12, 0x8a,
	0xa7, 0x9e, 0x9b, 0x91, 0x5f, 0xce, 0xd7, 0x8f, 0x03, 0x7f, 0x7e, 0xf1, 0x30, 0x56, 0x25, 0xe0,
	0x5a, 0x1c, 0xba, 0xf6, 0x3a, 0x70, 0x55, 0xc0, 0xcd, 0x81, 0x9b, 0xe3, 0x1a, 0x44, 0xd8, 0x3a,
	0xc9, 0x60, 0x12, 0x8a, 0xb7, 0xee, 0x18, 0xff, 0xe2, 0x5a, 0x74, 0xe8, 0x33, 0x5f, 0x38, 0x42,
	0xd7, 0xa2, 0x41, 0x97, 0x4a, 0x8f, 0x97, 0x73, 0x33, 0x58, 0x76, 0x07, 0xd2, 0x53, 0x1d, 0xac,
	0xd3, 0x42, 0xd8, 0x53, 0x1d, 0xac, 0xf3, 0x42, 0xd8, 0x53, 0x0d, 0xbc, 0x04, 0xbe, 0x36, 0xfd,
	0x89, 0x47, 0x4b, 0xdf, 0x42, 0xe9, 0xcb, 0x0e, 0xd7, 0x91, 0x11, 0xee, 0xcb, 0x0e, 0xd7, 0xa1,
	0x11, 0xee, 0xcb, 0x1a, 0xaf, 0x7f, 0x33, 0xd8, 0x4c, 0x8f, 0x84, 0x7b, 0xc8, 0x75, 0x3c, 0x22,
	0x45, 0x6b, 0x2a, 0x49, 0x89, 0x31, 0x05, 0xde, 0xc1, 0x66, 0xda, 0x0e, 0xb7, 0x14, 0xac, 0xaa,
	0x0a, 0x8a, 0x46, 0x15, 0x53, 0x86, 0xee, 0x8c, 0x48, 0xd1, 0xbe, 0x4a, 0x52, 0x62, 0xde, 0xd9,
	0xa4, 0x9b, 0x23, 0x52, 0xb4, 0xb4, 0x92, 0x94, 0x18, 0x5a, 0xd4, 0xdf, 0x19, 0xfc, 0x9b, 0x5f,
	0x1d, 0xef, 0x97, 0xef, 0xb2, 0xdf, 0xb0, 0xde, 0x48, 0x95, 0x94, 0x1a, 0x5f, 0x4c, 0x36, 0x53,
	0xd5, 0xd6, 0x0a, 0x6c, 0xa9, 0x33, 0x98, 0x6d, 0xa6, 0xac, 0x2d, 0x16, 0xd8, 0x52, 0x07, 0x21,
	0xea, 0x9f, 0x0c, 0x72, 0x3d, 0x0c, 0x3e, 0x2c, 0x7d, 0x6d, 0x35, 0x6f, 0x48, 0xb5, 0xa3, 0xe4,
	0x95, 0x88, 0xc9, 0x68, 0x1a, 0xdb, 0x72, 0xa1, 0x31, 0x79, 0x2f, 0xb3, 0xd1, 0x74, 0xb6, 0xf5,
	0x42, 0x63, 0xea, 0x72, 0x2a, 0xf1, 0x9e, 0xcf, 0x7f, 0xff, 0xfd, 0x5f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x72, 0x15, 0x95, 0x08, 0x0f, 0x04, 0x00, 0x00,
}
