# TODO
# - https://github.com/avelino/awesome-go#utilities  - click.octolab.net/github/retry
# - https://github.com/avelino/awesome-go#goroutines - click.octolab.net/github/semaphore
# - https://github.com/gohugoio/hugoDocs/issues/327
#   https://github.com/gohugoio/hugoDocs/pull/328    - click.octolab.net/github/forma

### API v1

GET http://localhost/api/v1/a382922d-b615-4227-b598-6d3633c397aa

###

GET http://localhost/github/click!

###

GET http://localhost/api/v1/09579e02-e076-489a-9741-f4cf2a67ad40

###

GET http://localhost/github/egg

###

GET http://localhost/api/v1/0d49a516-abea-430c-87a3-17992b8c6e45

###

GET http://localhost/github/forma

###

GET http://localhost/api/v1/19ac200a-ca74-48ca-8086-511f23d0c43e

###

GET http://localhost/github/retry

###

GET http://localhost/api/v1/4b1f1033-dd7c-452d-94bc-fe78591b7e66

###

GET http://localhost/github/passport

###

GET http://localhost/api/v1/7f9b8b84-977f-4fdb-a4df-fb17919fa897

###

GET http://localhost/github/semaphore

### Profiling

GET http://localhost:8090/pprof/cmdline

###

GET http://localhost:8090/pprof/profile

###

GET http://localhost:8090/pprof/symbol

###

GET http://localhost:8090/pprof/trace

###

GET http://localhost:8090/pprof

###

GET http://localhost:8090/pprof/goroutine

###

GET http://localhost:8090/pprof/threadcreate

###

GET http://localhost:8090/pprof/heap

###

GET http://localhost:8090/pprof/block

###

GET http://localhost:8090/pprof/mutex

### Monitoring

GET http://localhost:8091/expvar

###
